### ISSUE TITLE
Why do classes implement `hashCode` methods?

### ISSUE THREAD

**Issue by DanielSWolf** [js-joda/js-joda#103]
I noticed that just about every js-joda class implements a `hashCode` method.

I know that in Java, this method is inherited from `Object` and is used by classes such as `HashMap`. However, I've never seen `hashCode` methods in JavaScript Code. What's more, js-joda doesn't seem to use them, either. As far as I can tell, the only places where `hashCode` is ever called are other `hashCode` implementations.

So what's the reason for these methods?

**Comment by phueper** [comment]
Hi @DanielSWolf,

thanks for reporting this issue, i think you are right, these methods are possibly "leftovers" from java that we do not need... you *can* use them to compare instances (see https://github.com/js-joda/js-joda/blob/3aa18c9fd09ac52a0258828b2462d9bb0251eb94/CheatSheet.md#compare-localdates) ... how much sense that makes from a JS point of view can surely be debated... 
Our first topic when creating js-joda was to port the Java Code more or less completely, and we are still working on it or planning to do so (see #32 and #34 )  ...
One of our future plans https://github.com/js-joda/js-joda#future-milestones is to make the library more JS style (while keeping the API) and it is possible, that the hashCode() functions might be removed then.

Regards, Pattrick

**Comment by DanielSWolf** [comment]
Hi Pattrick,

Thanks for your explanation. I understand that you currently prioritize the implementation of missing features over code cleanup.

We're currently evaluating js-joda for an Enterprise application. If we decide to use it, I might be able to spare a bit of time for code cleanup -- things like this issue, issue #20 or issue #102. Would that be in your interest?

Daniel

**Comment by phueper** [comment]
Hi @DanielSWolf 

absolutely... That would be great! We are happy to get PRs to improve js-joda and work towards making it more usable :)

Regards, Pattrick

**Comment by pithu** [comment]
Hi @DanielSWolf

ack! Would be great to get PRs for things that we have on the road map anyway or if they are close to the threeten API.

Of course in some cases sticking to close to threeten makes no sense. Like for get and getLong because of the missing native types. And there are some places in the code, that could be solved much more elegant with a javascript style, like in the DateTimeFormatter.

hashCode is indeed questionable. At least immutable.js is using hashCode for hash calculation, but of course, it has a fallback. We might decide to move it outside and make it plugable.

**Comment by rpiaggio** [comment]
When working with Scala.js it makes a lot of sense to have the `hashCode` methods available, so that these classes can be used as keys in [Maps](http://www.scala-lang.org/api/2.12.1/scala/collection/Map.html). Therefore, I kindly request that `hashCode` methods are not removed. Thank you!
