### ISSUE TITLE
Converting LocalDateTime back to Instant with system timezone doesn't work

### ISSUE THREAD

**Issue by FreekPaans** [js-joda/js-joda#119]
When I'm trying to convert a LocalDateTime back to an Instant I'm getting an error when using the system default timezone:

```js
JSJoda.LocalDateTime.ofInstant(JSJoda.Instant.ofEpochSecond(1000), JSJoda.ZoneId.systemDefault()).toInstant(JSJoda.ZoneId.systemDefault())
```

I get an error:

```js
js-joda.min.js:13 Uncaught TypeError: t.totalSeconds is not a function(…)
```

When using UTC it works fine:

```js
JSJoda.LocalDateTime.ofInstant(JSJoda.Instant.ofEpochSecond(1000), JSJoda.ZoneId.UTC).toInstant(JSJoda.ZoneId.UTC)
=>
e {_seconds: 1000, _nanos: 0}
```

What am I doing wrong?

**Comment by pithu** [comment]
Hello @FreekPaans 

LocalDateTime.toInstant is only applicable for arguments of type ZoneOffset (fixed offset) but not for type  ZoneRegion. Actually the error is misleading, that's a bug i will fixed it, it should be an `IllegalArgumentException` with the message `zoneId should be instanceof ZoneOffset`

To get an instant of a LocalDateTime at a ZoneRegion convert it to a ZonedDateTime first:

```
const instant = Instant.ofEpochSecond(1000);
const zoneId = ZoneId.systemDefault();
LocalDateTime.ofInstant(instant, zoneId).atZone(zoneId).toInstant();
```

**Comment by FreekPaans** [comment]
@pithu thanks for the info. I'm not actually interested in doing things with zones, I'm just trying to convert the LocalDateTime back to an Instant. How would I do that?

**Comment by pithu** [comment]
@FreekPaans that's simply not possible.

An Instant represents a point in the timeline, a LocalDateTime can be any point in a range of the timeline. E.g. the LocalDateTime first of January, 2016, 2 pm in Europe/Berlin is a different point in timeline then at 2 pm in New York at the same date. 

To convert a LocalDateTime to an Instant you must supply a zone id e.q.:
```
LocalDateTime.parse('2016-01-01T14:00').atZone(ZoneId.UTC).toInstant()
```

**Comment by FreekPaans** [comment]
@pithu ok yeah that makes sense, and it works. Thanks!

I expected
```js
LocalDateTime.parse('2016-01-01T14:00').atZone(ZoneId.UTC).toInstant()
```
to be equivalent to
```js
LocalDateTime.parse('2016-01-01T14:00').toInstant(ZoneId.UTC)
```
But I guess don't fully understand everything yet.
Anyway, many thanks for your help!

**Comment by pithu** [comment]
@FreekPaans  both lines are equivalent for fixed ZoneOffsets, but second approach don't work for ZoneRegions (with daylight savings)
