### ISSUE TITLE
js-joda object to native Date object?

### ISSUE THREAD

**Issue by jsumners** [js-joda/js-joda#122]
Hopefully I'm only overlooking it in the documentation. How do you get a native `Date` from a `js-joda` object? For example:

```js
var jd = joda.ZonedDateTime.now().plusMinutes(30)
var d = jd.toDate() // jd.toDate is not a function
```

**Comment by pithu** [comment]
Use the static function convert for converting to a javascript native Date instance.
see https://js-joda.github.io/js-joda/esdoc/function/index.html#static-function-convert
```
const jd = joda.ZonedDateTime.now()
joda.convert(jd).toDate() // returns a javascript Date
joda.convert(localDate).toEpochMilli()   // returns the epochMillis
```

**Comment by jsumners** [comment]
Excellent. Thanks @pithu. 

I have to say, I think it would make much more sense for each type to have a `toDate` method.

**Comment by pithu** [comment]
Hi @jsumners thx for using js-joda and for your input.

For now we are concentrating to migrate the threeten API as is, without adding any additional stuff to the threeten classes. Therefore we put extra javascript stuff to separate functions/ classes.

We think about a [future milestone](https://github.com/js-joda/js-joda#future-milestones) 'make js-joda more javascript style', so your proposal is input for this one.
