### ISSUE TITLE
Change the private constructors to static private factory functions (`_ofXXX`)

### ISSUE THREAD

**Issue by phueper** [js-joda/js-joda#134]
As proposed in https://github.com/js-joda/js-joda/issues/131#issuecomment-280636063

Get rid of all(?) private constructors in js-joda and move them to private factory functions (`_of`)
So they do not appear in the esdoc and cannot cause confusion on how to create date objects

**Comment by pithu** [comment]
The trick with the static private factory function (`_of`) worx fine if there is a public and a private constructor, otherwise we can simply mark the constructor or the complete class as private in esdoc. 

I have checked all files in src/format

**Comment by phueper** [comment]
I just remembered... we also need to change the .d.ts file after the changes to "remove" the protected/private constructors from the typescript bindings

**Comment by pithu** [comment]
With version v1.3.1 all private constructors, function and classes are removed from esdoc and marked as deprecated in the typescript definition.

Version v1.4.0 removes the private constructors, function and classes from the typescript definition.  Typescript users might run in issues with this version. Typically a new instance in threeten are constructed by static factories, if you made it wrong and used a private constructors instead, replace it by a static factory. For the constructor of the DateTimeFormatterBuilder use the public variant with no arguments.
