### ISSUE TITLE
Test for mobile browsers

### ISSUE THREAD

**Issue by dwilmer** [js-joda/js-joda#135]
Hi all,

Do you have information on, or tests for, the performance of JS-Joda on mobile devices? First of all, because there are a lot of mobile visitors to web pages and secondly, it would be great to use this package in Cordova, where you build apps using html and javascript.
I would love to know whether js-joda, or what parts of js-joda, work on which mobile browsers (preferrably android 4.0 and up), and maybe help make it compatible.

Cheers!

**Comment by phueper** [comment]
Hi @dwilmer ...

Thanks for your question and for using js-joda :)

We have (manually) tested js-joda in mobile browsers in the past and it did work. 
As it is just plain JS i currently do not see a reason why it shouldn't work... 

We could think about running our tests in mobile browsers, our current browser testing provider saucelabs seems to also support that. We'll have a look.

Cheers, Pattrick

**Comment by phueper** [comment]
so... i added test launchers to also test js-joda in Android and iOS simulator on saucelabs ... the tests are running as expected :)

Regarding the performance, it is not easy to make a statement on that... i remember we tried to set something up on jsperf in the early days of porting js-joda, and it was faster than e.g. moment, but i think this really relates to the usecase... 
you could setup something on jsperf or other services that matches your usecase and have it tested with different browsers (mobile or desktop) or you could do some testing on a mobile device with a debugger connected and check the Developer Tools of e.g. chrome. I would expect js-joda to only use a fraction of the performance of a "normal" website  and things like layouting and rendering much more. But again, it depends on the usecase. 

If you are interested i could also check if i still find the things we did in jsperf and you can see wether they help you.

Cheers, Pattrick

**Comment by dwilmer** [comment]
Awesome, thanks!
Regarding performance: I meant it to mean "working as intended", not speed. In hindsight, this was a bad choice of words — maybe "usefulness" would have been better?

Anyway, it's great to see that it works on modern mobile devices. Based on [the Can I Use page for ECMAScript 5](http://caniuse.com/#feat=es5), I think most of it should work in most used browsers. The only problem I can think of is old behaviour of `parseInt`: in older versions (e.g. Android 4.2), having a string with leading zeroes would be parsed as octal. Therefore `parseInt('09')` returns `0` instead of `9` — `parseInt('09',10)` does return `9`. See also [this jsbin example](http://jsbin.com/sucohapuba/edit?html,js,output).
I'll test this when using it, and create a new issue and/or pull request if this pops up. Cheers!
