### ISSUE TITLE
What is the status of DateTimeBuilder?

### ISSUE THREAD

**Issue by memelet** [js-joda/js-joda#140]
I see that the tests are invoking and testing _methods. Is this is not yet "released"? And also its not exported by js-joda.js.

**Comment by phueper** [comment]
Hi @memelet,

please consider any functions or properties starting with `_` as being private/internal API that *should not* be used neither for reading nor writing.
*Some explanation:*
When porting the joda backport project to Javascript, we used this syntax (starting with `_`) to indicate the private properties and methods of Java. We also ported tests of the backport project. These tests can be found in the `/test/reference` folder. 
To increase the test coverage and to verify that our porting was working as expected, we also added tests in the main `/test` folder (outside of `reference`). It is true, that there are tests that use internal/private functions and methods as stated above (starting with `_`), but they should not be used by the "normal" users of js-joda. 

The public API of js-joda are the documented (https://js-joda.github.io/js-joda/esdoc/) classes and functions. We take care to keep these stable or if we need to introduce breaking changes we follow the semver (http://semver.org/) pattern and increase the version numbers accordingly.

Cheers, Pattrick

**Comment by phueper** [comment]
Hi again :) 

actually... we just realized that the `DateTimeBuilder` class itself is protected in the backport project https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/format/DateTimeBuilder.java#L95 ... so it itself should be considered as being not part of the public API. 
Thanks for finding this :) ... @pithu just removed it from the typescript definitions and the esdoc. I hope that makes it clearer. 

Regards, Pattrick

**Comment by memelet** [comment]
Thanks. Is bringing it in on the roadmap?

**Comment by phueper** [comment]
No it isn't... since js-joda is a port of the backport project (and its API) to Javascript, classes that are not part of the backport API should also not be part of the js-joda API.
