### ISSUE TITLE
FYI - Date Proposal

### ISSUE THREAD

**Issue by maggiepint** [js-joda/js-joda#142]
Hi, 

For lack of a more efficient way to contact you guys, I want you to know that I put this proposal on the agenda for the TC39 meeting next week to advance to stage 1: https://github.com/maggiepint/proposal-temporal

Your feedback along the way would be valued.

**Comment by phueper** [comment]
Hi Maggie, thanks for the info 👍, looks good, will watch the proposal.

Regards, Pattrick

**Comment by pithu** [comment]
Hi @maggiepint, 

awesome idea 👍  i will follow the proposal with great interest.

From a first reading of the proposal i have some first quick, unreflected ideas, comments:

- I like the idea of the idea with the `cap factories` like `LocalDateTime(...). Better then the bunch of .parse, .of, etc. factories of threeten.

- What about having factories  taking the iso8601 string like `LocalDateTime('2017-12-31T12:00:00')`, Could be extended by a formatter argument later on.

- Factories with long argument lists are quite unhandy and hard to read. What about allowing factories that are taking other domains like `ZonedDateTime(LocalDate(2012,12,13), LocalTime(11,55), zoneId)`

- Adding an option argument makes it even more unhandy, but is the option parameter really required ? Isn't the the ISO8601 calendar based on the Gregorian anyway ? And the resolver, isn't a default behavior enough for the most cases and can be omitted in the beginning ? (as far as i remember threeten is doing what you called next valid). And later it could be part of special special ZoneId supplying ZoneRules with a certain Resolver.

Regards and Good luck Philipp

**Comment by maggiepint** [comment]
Just FYI - I'm going to be at JSConf EU in Berlin in May. I think that you guys are in that part of the world. Going to be there? Would love to discuss in person if you are.

**Comment by phueper** [comment]
@maggiepint  i answered via mail, i think we don't need this issue anymore, will close it, discussion about the Date Proposal is in the proposal repo ..

**Comment by henryw374** [comment]
I realise it's early days, but what is your current view on proposal-temporal? 

It's a smaller api than 310, but for now at least it seems the objects it will have map 1-1 with 310. 

Are you thinking js-joda would use the platform ones directly, when available?

I'm not looking for any guarantees, but would be interested to know your thoughts.

Thanks

**Comment by phueper** [comment]
Hi,
well we are following the proposal discussions and sometimes give our oppinions... i for one am not happy with the `Civil` Prefix but that is under discussion...
I would certainly consider using the platform objects when available and useful, but as you said, it still is early stage for now.

Regards, Pattrick

**Comment by pithu** [comment]
I've just stumbled upon the current specification of `ZoneDateTime` in the `proposal-temporal`, and if it stays like that, it will be difficult or even impossible for us to stay compatible with the proposal.

Overall, I am quite disappointed how the proposal-temporal develops. It started very promisingly with a subset of JSR-310 domains. I had the hope that based on the JSR 310 (which was developed from `joda-time` over many years) a lightweight javascript API is created. Instead, the proposal sometime seemed to reset to 0, the focus was lost (for example, was talked about things like time on Mars). Personal interests are, in my opinion, placed above the interests of the community (as in the Local / Civil naming thing). Suddenly, the civil prefix was renamed to Gregorian (???) and many discussions seemingly are not conducted publicly.

Sure, it's all at an early stage, but I see in the end it will end up somewhere between the two extremes.

Either the proposal-temporal develops positively, ends up close to ThreeTen, then `js-joda` becomes obsolete for the javascript community and has its use only for Java cross compiler tools.

Or the other extreme, it is developing negatively in our view, with many name clashes and incompatible concepts. Then, sooner or later, we'd probably develop our own lighter-weight, javascript-like API and put it before the ThreeTen API.
