### ISSUE TITLE
Question: Ultra verbose rendering of ZoneId when using chai.js

### ISSUE THREAD

**Issue by memelet** [js-joda/js-joda#143]
When using chai and chai displays a diff for assertion failure the ZoneId is rendered along with all the timezome rules (using js-joda-timezone of course). eg

```
  {
    "device_uuid": "device-1"
    "end": {
      "_dateTime": {
        "_date": {
          "_day": 13
          "_month": 3
          "_year": 2017
        }
        "_time": {
          "_hour": 10
          "_minute": 0
          "_nano": 0
          "_second": 0
        }
      }
      "_offset": {
        "_id": "+01:00"
        "_rules": {
          "_offset": [Circular]
        }
        "_totalSeconds": 3600
      }
      "_zone": {
        "_id": "Europe/Berlin"
        "_rules": {
          "_ldtUntils": {
            "_ldtUntils": [
              [undefined]
              [undefined]
              [undefined]
              [undefined]
              [undefined]
              [undefined]
              ...
              ...
```

Is this because ZoneRegion does not implement a nicer toString()

**Comment by memelet** [comment]
Other quirks. All the functions also show up in the diff. Maybe there is is just an issue with chai and nothing can be done here. Just checking if anyone has encountered this and maybe has some tips.

**Comment by memelet** [comment]
Little trick that pretty does the job
```
function eqlOccurance(expected) {
  const actual = this._obj
  const ejson = JSON.stringify(expected, null, 2)
  const ajson = JSON.stringify(actual, null, 2)
  return new chai.Assertion(ajson).to.be.eql(ejson)
}
chai.use((C, _) => {
  C.Assertion.addMethod('eqlOccurance', eqlOccurance)
})
```

**Comment by pithu** [comment]
The above structure looks like the internals of a ZonedDateTime instance. ZonedDateTime and all other js-joda objects are implementing `toString()` and `toJSON()`. Therefore `JSON.stringify(expected)` is the same as `expected.toString()` if expected is a js-joda instance. So  it must be some issue with your code.

Tip: For comparing two js-joda Objects favor the js-joda equals methods over a deep equal of an extarnal lib.  

```
   // Good
    expect(zonedDateTime1.equals(zonedDateTime2)).to.be.true()

   // Bad
    expect(zonedDateTime1).to.deep.equal(zonedDateTime2)
```

**Comment by phueper** [comment]
According to https://github.com/chaijs/chai/issues/469#issuecomment-112343104 it could be a problem with the testrunnner, not with chai itself... maybe the testrunner is not using the `toString()`/`toJSON()` ?

**Comment by memelet** [comment]
The objects I am comparing are not just joda objects, but rather contain joda objects. So I can't just use `zdt1.equals(zdt2)`. But I also was not using `deep`, just `to.be.eql`, eg:

```
const o1 = {foo: 'foo', zdt: ZonedDateTime.parse(...)}
const o2 = {foo: 'foo', zdt: ZonedDateTime.parse(...)}
expect(o1).to.be.eql(o2)
```

It was in this case that the output of internals above was rendered by mocha's diff. And even when I manually removed the zone objects before comparison all the functions names were then rendered by mocha's diff.

**Comment by memelet** [comment]
@phueper Yes, it looks most likely to be a mocha issue.

**Comment by memelet** [comment]
However it does look like mocha would use `JSON.stringify` to render joda objects (https://github.com/mochajs/mocha/blob/7493bca76662318183e55294e906a4107433e20e/lib/utils.js#L472)

**Comment by phueper** [comment]
If you are wrapping them, then i would guess your wrapper objects should implement toString and toJSON to make it work?

**Comment by memelet** [comment]
Yes, but right now they are just js objects not classes. Anyway, I was wondering if anybody else ran into this. I'll close the issue. Thanks!
