### ISSUE TITLE
some classes not listed in dist

### ISSUE THREAD

**Issue by henryw374** [js-joda/js-joda#150]
Hi,

Navigating under the JSJoda object I get when importing  _https://rawgit.com/js-joda/js-joda/master/dist/js-joda.js_ , I see it is missing some things from the api, for example **Temporal** or **TemporalAccessor**. Would it be possible to have a way to access these things other than via this sort of thing?

`JSJoda.DayOfWeek.FRIDAY.__proto__`

Thanks

**Comment by phueper** [comment]
Hi @henryw374,

thanks for reporting... the "scope" of the js-joda.js is for users of the library... for our "plugins" e.g. js-joda-locale, we are actually thinking about how we can give access to more parts of the API that "normal" users don't necessarily require ... Could you give us an example to understand how you would use the `Temporal` and `TemporalAccessor` classes... it might help us decide how to handle these :)

Regards, Pattrick

**Comment by henryw374** [comment]
Ok cool so this would be useful in creating a Clojurescript wrapper for js-joda. Currently there is a  [Clojure (jvm) wrapper for this](https://github.com/dm3/clojure.java-time) and the plan is to provide the same api for a Clojurescript version. 

This new wrapper will ideally share much of the code of the Clojure version and that version already uses things like Temporal for polymorphic dispatch.
