### ISSUE TITLE
Compare with date-fns?

### ISSUE THREAD

**Issue by rauschma** [js-joda/js-joda#172]
It’d be nice if there were a brief comparison with date-fns in the readme, to help with evaluating js-joda.

**Comment by pithu** [comment]
I am not sure, is the js-joda repo, especially the readme the right place for that?

If you know a good blog post, that is comparing JavaScript Date and Time APIs, we could add a link to it in the readme.

Btw: There is this nice talk from Matt Johnson about the [JavaScript Date and Time APIs](https://youtu.be/aVuor-VAWTI)  moment, date-fns, js-joda and the tc39 temporal proposal.
