### ISSUE TITLE
Turn getter methods into real native getters

### ISSUE THREAD

**Issue by buschtoens** [js-joda/js-joda#184]
Since [native getters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) are well supported, even in IE 9, it would be great, if js-joda could switch getter methods to real getters with the next major version bump.

This would make js-joda easier to integrate into other frameworks. For example, user could directly access properties in their templates:

```hbs
Year of birth: {{birthdate.year}}
```

Or easily mangle data:

```js
const users = {
  'fred':    { 'user': 'fred',    'birthdate': LocalDate.of(1980, 4, 3) },
  'pebbles': { 'user': 'pebbles', 'birthdate': LocalDate.of(1995, 7, 24) }
};

_.mapValues(users, 'birthdateyzear');
// => { 'fred': 1980, 'pebbles': 1995 } 
```

I'm currently working on [ember-joda](https://github.com/buschtoens/ember-joda), an Ember.js addon that aims to make joda as compatible and easy to use as possible. For that I'm twisting and turning the original source code with Babel transforms.

One simple, but powerful fix is changing a getter method to a real getter:

- [method to getter](https://github.com/buschtoens/ember-joda/blob/e7ac9453eb603c1b001975d16c3aa5eefa88e1bd/lib/transform-joda-to-ember/index.js#L130-L136)
- [call expression to member expression](https://github.com/buschtoens/ember-joda/blob/e7ac9453eb603c1b001975d16c3aa5eefa88e1bd/lib/transform-joda-to-ember/index.js#L142-L150)

**Comment by pithu** [comment]
Hello @buschtoens 

Thx for your proposal. We also had considered to switch the getters to `native getters` with a next major release. I will add it to the [future-milestones](https://github.com/js-joda/js-joda#future-milestones) of the Readme.
