### ISSUE TITLE
Add "constant" DateTimeFormatter definitions

### ISSUE THREAD

**Issue by phueper** [js-joda/js-joda#194]
e.g. ISO_LOCAL_DATE, ISO_WEEK_DATE, ...

and the corresponding tests from `TestDateTimeFormatters`

we found out in #192 that these are missing currently

**Comment by xenoterracide** [comment]
+1 https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_LOCAL_DATE

**Comment by xenoterracide** [comment]
actually on second glance it looks like this is in there, just needs documentation?

**Comment by InExtremaRes** [comment]
Has this been resolved by #455?

**Comment by pithu** [comment]
Yes thanks to @akonior
