### ISSUE TITLE
toString() leaving out seconds...

### ISSUE THREAD

**Issue by djlogan2** [js-joda/js-joda#205]
Why in the world would ZonedDateTime leave the seconds out of the formatted string?

```
const when = Joda.ZonedDateTime.of(2017, 12, 25, 13, 15, 0, 0, Joda.ZoneId.of('America/New_York'));
console.log(when.withFixedOffsetZone().toString());
```
2017-12-25T13:15-05:00

I have to figure out how to fix this because when I try to use this not-quite-iso-date, the google calendar API fails with a malformed date (at '-05:00'.)

Thank you,
David Logan

**Comment by djlogan2** [comment]
I see. According to the documentation, leaving the seconds off is an ISO standard if the seconds are zero. I don't know if that's true, but that's what the documentation says. I suppose I will have to use a formatter and force it to write the seconds. Thanks!

**Comment by phueper** [comment]
Hi @djlogan2,

i will close this issue, since you found the solution yourself, feel free to reopen if you have further questions

Regards, Pattrick
