### ISSUE TITLE
OffsetTime missing

### ISSUE THREAD

**Issue by henryw374** [js-joda/js-joda#240]
Hi, 

Firstly thanks for js-joda! I would like to know if you have plans to implement OffsetTime? 

I found another ticket discussing OffsetDateTime https://github.com/js-joda/js-joda/issues/165 and with that one it seems to make sense that the functionality already exists. 

Thanks,
Henry

**Comment by pithu** [comment]
Hello @henryw374 

Unfortunately the situation did not change since #165, we have no plans to implement OffsetTime or OffsetDateTime, but we would accept a PR.

**Comment by henryw374** [comment]
Ok thanks... Might try that if I have time

**Comment by henryw374** [comment]
work started in this fork https://github.com/henryw374/js-joda
