### ISSUE TITLE
Clock.offset not implemented

### ISSUE THREAD

**Issue by henryw374** [js-joda/js-joda#245]
I'll aim to do a PR if I have time

**Comment by henryw374** [comment]
It would be handy to have as part of the docs a list of classes and methods in http://www.threeten.org/threetenbp/ that are still to be implemented. Is there such a list anywhere?

Thanks

**Comment by henryw374** [comment]
created PR https://github.com/js-joda/js-joda/pull/246

**Comment by pithu** [comment]
Hi @henryw374,

sorry, no we do not provide any snapshot releases, so i just published a release, hope that helps. 

Regards

**Comment by henryw374** [comment]
Thanks!
