### ISSUE TITLE
Partial

### ISSUE THREAD

**Issue by singingwolfboy** [js-joda/js-joda#256]
Joda-Time in Java has a [Partial class](http://www.joda.org/joda-time/key_partial.html), which can represent any set of partial datetime values. js-joda has a few classes to represent partial datetime values (Year, YearMonth, Month, MonthDay, etc) but it does not have this generic Partial class that encompasses all of them.

How difficult would it be to add this feature? I'm happy to help if I can, but I've never used this library before, and I don't know how to begin.

**Comment by pithu** [comment]
js-joda is not a port of Joda-Time but from the successor project threeten. It has the same author and similar concepts, but is different. Threeten is somehow the base for JSR-310/ java 8 time api. 

I am sorry, but we are quit strict in following the [threeten API](http://www.threeten.org/threetenbp/) and wouldn't add anything that is not part of threeten.

**Comment by singingwolfboy** [comment]
Alright. In that case, what is the recommended way to parse strings that may or may not be fully specified datetimes?

For example, I'd like to write a piece of code that can correctly parse any of these strings: `2018-01-04`, `2018-01`, `--01-04`, `2018`. Should I just use multiple nested `try`/`catch` blocks to check for each format?

**Comment by pithu** [comment]
There might be a more sophisticated solution for your problem, but you have to dive quite deep into the threeten API. There is a section about custom formatters and queries in the [js-joda cheatsheet](https://js-joda.github.io/js-joda/cheat-sheet.html#custom-formatter-and-queries). The trick described in the cheatsheet is two define a pattern with some optional sections and then hook into the queryFrom callback. There you can check what kind of objects are detected in your parser query. But i am not sure if you can solve your issue with that.

**Comment by phueper** [comment]
For parsing you might be able to use optional patterns using `[` `] ` (https://js-joda.github.io/js-joda/esdoc/class/src/format/DateTimeFormatter.js~DateTimeFormatter.html)

I can't try your examples right now, but i think it should work to make the individual parts optional

**Comment by pithu** [comment]
Does our answers solve your issue? Can we close it?

**Comment by singingwolfboy** [comment]
Yes, thank you.
