### ISSUE TITLE
No TypeScript definition for DateTimeParseException

### ISSUE THREAD

**Issue by singingwolfboy** [js-joda/js-joda#257]
When trying to do `import { DateTimeParseException } from "js-joda"` in a TypeScript file, I get the following error:

```
[ts] Module '"node_modules/js-joda/dist/js-joda"' has no exported member 'DateTimeParseException'.
```

Looks like the type definition is missing for this exception. Could they be added? Unfortunately, I'm new to TypeScript, and I don't know how to do this myself.

**Comment by pithu** [comment]
Fixed with #258
