### ISSUE TITLE
is LocalTime.toJSON necessary?

### ISSUE THREAD

**Issue by simonfox** [js-joda/js-joda#267]
First thanks for the great work on js-joda!

Just wondering about the reasoning behind and implementation of the `toJSON` implementation provided on `LocalTime` is.

We have a convention that property names ending with `time` should be deserialized to LocalTime which we can do with a globally registered reviver on our http client. Now when we want to send a time value back, we have a requirement to provide it formatted as `HH:mm:ss` in all cases.  It would be nice to do this via a global replacer on the http client - and we can - it's just the implementation has to be `LocalTime.parse(propertyValue).format(DateTimeFormatter.ofPatter('HH:mm:ss');`. The initial parse is required because `JSON.stringify` calls `LocalTime.toJSON` _before_ invoking the replacer for the time property.

Do you have any suggestions or do I just need to stick with the `format(parse(value))` solution?

**Comment by pithu** [comment]
We implemented `toJSON` so that `JSON.stringify()` prints a parseable string. If you want a custom format, you have to specify it.
