### ISSUE TITLE
Does js-joda support locales?

### ISSUE THREAD

**Issue by DanielSWolf** [js-joda/js-joda#272]
According to the Readme file, locale support is planned for a (future) milestone 3. At the same time, there is an official `js-joda-locale` package that has been released for about a year. Could you tell me the current status?

* Does js-joda support localized strings for days of the week, months etc?
* Does js-joda support localized rules for first day of the week, first week of the year, etc.?
* If so: What features are currently missing?

**Comment by phueper** [comment]
Hi @DanielSWolf 

thanks for using js-joda and thanks for the question :) 

`js-joda` itself does not support locale, we decided to split the library in the core (`js-joda`) part and have "plugins" providing additional functionality (e.g. timezone support in `js-joda-timezone`, locale support in `js-joda-locale` )
So, the answer to your questions would be "Yes, we support these features as far as they are supported by the threeten api" ... the implementation is in `js-joda-locale` ... "
However, `js-joda-locale` is not very easy to use, needs additional build steps to build locale pacakges.. i have tried to split it up in several locale specific packages, but ran into problems with npm name rules (too many `-` and `_` in `js-joda-locale_en-US` ) ... 
And... i kind of ran out of time in the last months ... 
Our plan is to update `js-joda-locale` to new dependencies and then release it in the `@js-joda/locale_xx-XX` namespace (hopefully solving the problem with naming) ...  

I hope it answers your questions... and ... these questions motivate me to sit down and get some work on it done, when we see, that people actually need these features :) ... so ... keep the "pokes" coming :)

Regards, Pattrick

**Comment by DanielSWolf** [comment]
Thanks for the clarification! :-)

**Comment by phueper** [comment]
@DanielSWolf  

fwiw ... i just published `@js-joda/locale` and `@js-joda/locale_xx-xx` ... 

i'm happy for any feedback :)
