### ISSUE TITLE
Reconsider add again private constructors to typescript type definitions

### ISSUE THREAD

**Issue by InExtremaRes** [js-joda/js-joda#279]
Many constructor in this projects are private. Since they are no intended to be used from clients of the library they should be marked as such in .d.ts files. I think this used to be the case (see ecba785a495a3beec660a4c3208561a5b5d6bb1a and [#134-comment](https://github.com/js-joda/js-joda/issues/134#issuecomment-280951131)) but then they were removed.

If a class lacks a `constructor` declaration the class is still constructible (with a default, zero-argument constructor). So, the next snippet will fail at runtime but not at type-checking

```ts
const x = new Instant(); // Compiler is happy
```

This is wrong since, a) the constructor (right now) expects two arguments, and b) it is not expected to instantiate the class like that. When I'm using TypeScript I expect to be notified at type-checking of this misuses, right now and while I'm learning the API this is confusing.

Adding a `private constructor` declaration will prevent this, even if the constructor has no parameters:

```ts
// Somewhere inside the type definition
class Instant extends Temporal {
    // ...
    private constructor();
    // ...
}

const x = new Instant(); // ERROR: Constructor of class 'Instant' is private and only accessible within the class declaration
```

So, please reconsider to add those declarations again.

**Comment by pithu** [comment]
Hello @InExtremaRes,

we are not that firm with typescript, the commits came mainly from the community. Do you suggest to add definitions like that `private constructor(...)` to the .d.ts file ? Sounds good, could you provide a PR for that ?

Regards Philipp

**Comment by InExtremaRes** [comment]
@pithu That's my suggestion, indeed. I'm very short of time right now, but if within a couple of weeks this is still open I could probably work on it. Just some questions in the meanwhile. How much the constructors are "implementation details"? How do you address extensions? Are clases designed to be extended (read inherited)?

Let me clarify. In JavaScript everything is public, everything is dynamic and every class is extensible. TypeScript add some type checking that can express better the intentions behind a design. Since you are not using TypeScript in this project, some decision need to be made afterwards.

As I said, it's enough to add some, zero argument, `private constructor()` declarations. This at least prevents users of the library to instantiate with `new`. If constructors are _really_ private and can vary without warning this is maybe a good approach. But then, in a TypeScript project, I won't be able to extend that class since constructor is private. If you allow clients of the library to extend the classes, I suggest to declare the constructors as `protected` with the right arguments and keep them in sync with implementation.

**Comment by InExtremaRes** [comment]
BTW This is that kind of project that could benefit on using TypeScript.

**Comment by pithu** [comment]
It depends, best way is probably to follow the classes of the [threeten backport](https://github.com/ThreeTen/threetenbp/tree/master/src/main/java/org/threeten/bp). There are final classes like `LocalDate` with `private` constructors and abstract classes  like `ChronoLocalDate` and interfaces like `Temporal` that probably need a protected constructor in TypeScript.
