### ISSUE TITLE
Display name for a Month

### ISSUE THREAD

**Issue by NickDarvey** [js-joda/js-joda#281]
I understand that `Month.getDisplayName()` is [currently in a TODO state](https://github.com/js-joda/js-joda/blob/8af1100f693bd3033ab06f9cf0ea2693a58bfcf3/src/Month.js#L73), but is there another way to get the display name of a `Month`?

I had a look at `js-joda-locale` and whilst it looks like it can format and localize months in a `LocalDateTime`, I couldn't see any references to formatting a `Month` on its lonesome. 

I was thinking perhaps I would bring the `Month` into a `LocalDateTime` and format it as 'MMMM', unless there's a better option I'm overlooking.

**Comment by phueper** [comment]
Hi,

Thanks for using js-joda and thanks for the report. I'm afraid using a `LocalDate` and formatting it using `MMMM` using js-joda-locale to get the month display name is currently the only way to get it. we are thinking about ways to detect that js-joda-locale has been loaded and then automatically returning the displayName from `getDisplayName` but that is not coming very soon I'm afraid

Regards, Pattrick

**Comment by NickDarvey** [comment]
That does the trick. Thanks Pattrick!

```javascript
import { Month, LocalDate, DateTimeFormatter } from 'js-joda';
import { Locale } from '@js-joda/locale_en';

const month = Month.JANUARY;
const monthDisplayNameFormatter = DateTimeFormatter.ofPattern('MMMM').withLocale(Locale.UK);
const monthDisplayName = LocalDate.of(1, month, 1).format(monthDisplayNameFormatter);
console.log(monthDisplayName); // prints 'January'
```

**Comment by alamothe** [comment]
Same for `DayOfWeek`. Any plans to get this done soon?
