### ISSUE TITLE
Add Chrome DevTools Custom Object Formatters?

### ISSUE THREAD

**Issue by benny-medflyt** [js-joda/js-joda#282]
Right now, when you use the devtools debugger to view a js-joda object, or use "console.log" to print it, it prints the internal structure of the object:

    Instant {_seconds: 1508177614, _nanos: 383000000}

While this is cool to see these guts, it is almost never useful, and would be much more helpful if it were printed in a more human friendly form, such as:

    Instant 2017-10-16T18:13:34.383Z

This is possible using Chrome DevTools custom object formatters:
  - <https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/edit#heading=h.xuvxhsd2bp05>
  - <https://github.com/andrewdavey/immutable-devtools>

Adding support for custom formatters is non intrusive to this library. It could be added directly to this library, or as a separate library.

The implementation would be very simple and short, a nice implementation would simply be the type of the object followed by calling toString() on it, and possibly adding some nice coloring for each different type of joda object.

**Comment by pithu** [comment]
Hello @benny-medflyt 

Nice idea, open for that, i would see it in a separate library, but i currently would not work on it.
