### ISSUE TITLE
Formatting with locales in Typescript

### ISSUE THREAD

**Issue by jonfreedman** [js-joda/js-joda#285]
As per [the docs](https://js-joda.github.io/js-joda/manual/formatting.html#formatting-with-locales) we should import a `@js-joda/locale_` package and call the `DateTimeFormatter#withLocale` method in order to use ee or MMM formats.

I see the typescript definition was fixed to add a `Locale` parameter in https://github.com/js-joda/js-joda/commit/2f65f8be8fe4898731663ec268dc7e16a5706c86 but I could not find the definition of the Locale type nor any type definition for the js-joda-locale packages...

Could you please look into adding typings for js-joda-locale and cutting a release of js-joda with the updated typings?

**Comment by jonfreedman** [comment]
I ended up with this as a local typescript definition if it can be incorporated into a release

```typescript
declare module "@js-joda/locale_en" {
    export interface LocaleInstance {
        language: () => string;
        country: () => string;
        localeString: () => string;
        toString: () => string;
        equals: (other: any) => string;
    }

    export interface LocaleStatic {
        UK: LocaleInstance;
        new(): LocaleInstance;
    }

    export const Locale: LocaleStatic;
}
```

**Comment by phueper** [comment]
Hi @jonfreedman  ... thanks for this  report... i'll try to incorporate it into js-joda/locale

Regards, Pattrick

**Comment by JKillian** [comment]
Just hit this myself, do you know if the fix from https://github.com/js-joda/js-joda/commit/2f65f8be8fe4898731663ec268dc7e16a5706c86 will be released anytime soon? Great library btw!

**Comment by dgreene1** [comment]
I'd also like to know when https://github.com/js-joda/js-joda/commit/2f65f8be8fe4898731663ec268dc7e16a5706c86 will be released. Thank you for your great work! :)

**Comment by phueper** [comment]
@jonfreedman @JKillian @dgreene1 

we did recently release updated .ts bindings of @js-joda/core and updates of @js-joda/locale_* ... could you please try if your probems are resolved?

**Comment by phueper** [comment]
i'll close this issue for now, feel free to reopen if the problems still occur

**Comment by JKillian** [comment]
Hi @phueper, just tried out the latest versions, and the types for `withLocale` seem to be working well, thank you!  I did notice however that `@js-joda/locale_en-us` doesn't seem to have any types with it, so I still have to do a bit of manual work to be able to import it properly, something like this:

```ts
declare module '@js-joda/locale_en-us' {
  import { Locale as LocaleType } from '@js-joda/core';
  declare const Locale: { US: LocaleType };
}
```

**Comment by dgadelha** [comment]
The problem still occurs with specialized locale packages as mentioned previously by @JKillian

**Comment by dgreene1** [comment]
I feel like the local package should either make this automatic, or it should have documentation to do @JKillian's suggestion (https://github.com/js-joda/js-joda/issues/285#issuecomment-560434516)
