### ISSUE TITLE
Fix typescript definitions for DateTimeFormatterBuilder#appendValue and #appendValueReduced

### ISSUE THREAD

**Issue by jonfreedman** [js-joda/js-joda#286]
Currently these are defined in `js-joda.d.ts` as no-arg methods

**Comment by phueper** [comment]
Hi @jonfreedman  ... thanks for reporting ...would you mind creating a PR for this? 

We are not much of typescript users, the `.d.ts` files have mostly been community contributed

Regards, Pattrick
