### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by alamothe** [js-joda/js-joda#315]
Thanks for the great library!

Still, bundle size is quite large (4x of moment). 

One idea how to reduce it would be to move all printing/parsing into a separate package. For some use cases (browser), it might be perfectly fine to use `Intl` for formatting while still using this library for underlying calculations. Similar approach is taken by Luxon.

What are your thoughts?

**Comment by pithu** [comment]
Yes great idea, since `Intl`  is supported by most browsers, sounds like an interesting approach. We had some other ideas in the past to reduce bundle size, like having a subset just with LocalDate, LocalTime LocalDateTime.  

Well, but unfortunately its not trivial to implement...

**Comment by alamothe** [comment]
Thank you for your reply!

How about something similar to how `js-joda-locale` works? Leave parsing and formatting functions (e.g. `ZonedDateTime.format`) as a single throw statement in their bodies, and augment from the parsing/formatting package.
