### ISSUE TITLE
Period 'PT0S'

### ISSUE THREAD

**Issue by robotnic** [js-joda/js-joda#329]
Isn't "PT0S" a valid Period?

```
const jsJoda = require('js-joda');

jsJoda.Period.parse('PT0S');

```
DateTimeParseException: Text cannot be parsed to a Period: PT0S, at index: 0

**Comment by pithu** [comment]
Period is for a `date-based` amount of time, for `time-based` values use Duration.

```Duration.parse('PT0S')``` should work

**Comment by pithu** [comment]
Is the issue solved ? Feel free to reopen it again.
