### ISSUE TITLE
Add pattern parser/ formatter for numbers

### ISSUE THREAD

**Issue by pithu** [js-joda/js-joda#33]
The js-joda release v1.0  has support for  iso date/time formats such as ISO_LOCAL_DATE_TIME ('2011-12-03T10:15:30') and ISO_ZONED_DATE_TIME ('2011-12-03T10:15:30+01:00[Europe/Paris]')

Still missing is support for building a formatter/ parser by a pattern. see  [DateTimeFormatter.ofPattern](http://www.threeten.org/threetenbp/apidocs/org/threeten/bp/format/DateTimeFormatter.html#ofPattern-java.lang.String-) for a description.

In a first step functionality for "number patterns" can be ported, without any support for "text patterns", so no locale text db is required.

**Comment by phueper** [comment]
I started on DateTimeFormatter.ofPattern / DateTimeFormatterBuilder.appendPattern for Year.parse

**Comment by phueper** [comment]
initial version of DateTimeFormatter.ofPattern / DateTimeFormatterBuilder.appendPattern without support for localized texts is in https://github.com/phueper/js-joda/tree/year_impl  .. i'll assign this to me :)

**Comment by phueper** [comment]
Not everything seems to be working, e.g.

var f = DateTimeFormatter.ofPattern("yyyy-MM-dd”)
LocalDate.parse('2012-02-24', f)

is not working while parsing "u M d" is working... i'll reopen to investigate

**Comment by phueper** [comment]
Closed with release 1.1.1... Seems to work now
