### ISSUE TITLE
Add pattern parser/ formatter for text with locale support 

### ISSUE THREAD

**Issue by pithu** [js-joda/js-joda#34]
Based on issue #33 implement support for text patterns with locale support for the DateTimeFormatter.

For locale database check [mdn Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) and the locale database of [momentjs](https://github.com/moment/moment/)

**Comment by NicoleRauch** [comment]
Is this the reason why the invocation `DateTimeFormatter.ofPattern("d MMM yyyy")` explodes with 

`IllegalArgumentException: Pattern using (localized) text not implemented yet!
    at DateTimeFormatterBuilder._parseField (node_modules/js-joda/dist/js-joda.js:4648:11267)
    at DateTimeFormatterBuilder._parsePattern (node_modules/js-joda/dist/js-joda.js:4648:7785)
    at DateTimeFormatterBuilder.appendPattern (node_modules/js-joda/dist/js-joda.js:4648:6023)
    at Function.ofPattern (node_modules/js-joda/dist/js-joda.js:5624:74)
`

?

**Comment by phueper** [comment]
Hi Nicole,

yes it is. `MMM` would result in a localized Text representation of the MonthOfYear. `DateTimeFormatter.ofPattern("d MM yyyy")` should work though

Regards, Patty

**Comment by NicoleRauch** [comment]
Thanks for the quick answer! It's a bit misleading that the documentation of this method gives this exact example ;-)

**Comment by phueper** [comment]
I agree... i created a new issue to clarify this in the documentation.

**Comment by NicoleRauch** [comment]
Thanks! I really appreciate your responsiveness :-)

**Comment by phueper** [comment]
And we appreciate your feedback ;-)

**Comment by soc** [comment]
@pithu We use https://github.com/cquiroz/scala-java-locales for JavaScript locale support in https://github.com/soc/scala-java-time, maybe you can adapt @cquiros' code for your purposes? I investigated `Intl.DateTimeFormat` before and sadly it seems to be of web quality.

**Comment by sadevelopment** [comment]
Is there an ETA on localised text - its been a while since this issue was raised and its still outstanding ... it would be handy to have as we are trying to parse RFC2616 dates from responses ... if not can you suggest and alternative library to js-joda?

**Comment by 807811b0-1373-11e5-b60b-1697f925ec7b** [comment]
My team uses https://github.com/moment/moment but we wanted to switch over to js-joda once this issue is resolved.

**Comment by sadevelopment** [comment]
Funnily enough - I have literal just started integrated it within the last 10 minutes. Thanks for the response.

**Comment by phueper** [comment]
hi, thanks for your interest.

i'm sorry to say, that we can currently not give an ETA on this issue, both @pithu and i are pretty busy outside of js-joda currently and cannot say when and how we can tackle this problem :/
We understand that it is a last big missing piece.
We would love contributions regarding this topic though and would be more than happy to give support if any volunteers want to try to tackle it :)

Cheers, Pattrick

**Comment by kernwig** [comment]
How about just removing the exceptions? I'm just trying to use `DateTimeFormatter.ofPattern('h:mm:ss a')`. It throws on 'a', but there's unreachable code after it. Maybe not all locales will be supported, but you can at least make all of your work usable for _part_ of the world.

**Comment by phueper** [comment]
ok, ok... you piqued my curiosity... i started to look into this a little more and it doesn't seem to be *that* hard... you might wanna start looking at https://github.com/js-joda/js-joda-locale ... the functionality will be a plugin and implemented there... but don't expect it to be really quick... no ETA still :) ...

**Comment by kernwig** [comment]
Cool. Certainly too late for my current project, but glad the library is going to move forward.

**Comment by sadevelopment** [comment]
Cool indeed - I have used moment for the moment (lol) just for the missing part. I will definitely be swapping back though as the rest is js-joda. Keep up the good work and look forward you finishing off with js-joda ...

**Comment by phueper** [comment]
fyi to anyone interested... the first very basic functionality is starting to be there... https://github.com/js-joda/js-joda-locale... i will probably set up infrastructure (testing/travis/...) when i get to it in the next weeks and might release a 0.1 afterwards... but beware... probably lots of bugs and open ends currently

**Comment by phueper** [comment]
we released the first version of js-joda-locale 0.1.0 ... https://github.com/js-joda/js-joda-locale/releases/tag/v0.1.0    feedback very much welcome

**Comment by phueper** [comment]
.. getting close to a 1.0 of `js-joda-locale` (and closing this issue :)) ... 

https://github.com/js-joda/js-joda-locale/releases/tag/v0.8.0

Functionality should be complete now

**Comment by phueper** [comment]
we just released a 1.0 of `js-joda-locale` ...

https://github.com/js-joda/js-joda-locale/releases/tag/v1.0.0

:tada:  ... i will happily close this issue :)

**Comment by pithu** [comment]
🎉
