### ISSUE TITLE
@js-joda/extra Type Definitions not yet published.

### ISSUE THREAD

**Issue by mg-vmoaero** [js-joda/js-joda#346]
Is there a timeline planned for publishing this package with the type definitions?

Typescript is quite popular and having to '@ts-ignore' every time I import Interval and keep a webpage up with the documentation (that's sometimes wrong, due to being lifted from jodatime which I understand) so I know what methods I can use is pretty frustrating at times.

**Comment by pithu** [comment]
Hi @mg-vmoaero 

I just released @js-joda/extra@0.3.0. Have fun.
