### ISSUE TITLE
[core] Missing static methods in TypeScript definitions

### ISSUE THREAD

**Issue by InExtremaRes** [js-joda/js-joda#349]
Some classes has missing or wrong static methods definitions. For instance, [definitions for LocalDateTime](https://github.com/js-joda/js-joda/blob/master/packages/core/dist/js-joda.d.ts#L923) says that all parameters of `of()` are optional but that isn't true. Also there is no definition for `ofNumbers`, `ofDateAndTime`, etc. Same happens in other classes.

I could give that a try and send a PR if none else can. All those static methods are public (`ofNumbers` and so on)? Are public all of those `of2`, `of8`, etc?

**Comment by lppedd** [comment]
@InExtremaRes hi!
About the `of()` method. The two TS definitions are correct.  
The `of()` with > 2 parameters calls `ofNumbers`, which has this signature
```
static ofNumbers(year=0, month=0, dayOfMonth=0, hour=0, minute=0, second=0, nanoOfSecond=0) { ... }
```
There is not really a use of having `ofNumbers` and `ofDateAndTime` exported, as they're represented by the two `of` variants.

@pithu is my understanding correct?

**Comment by pithu** [comment]
Yes that's sounds correct. `ofNumbers` and `ofDateAndTime` shouldn't be part of the public API. 
We are open for Pull Requests ;)

**Comment by lppedd** [comment]
@pithu than I don't think this issue requires a PR at all.
I've seen you guys manually add definitions, have you considered automating it?
Now, with TS 3.7 this is possible https://github.com/microsoft/TypeScript/issues/7546

**Comment by pithu** [comment]
Ah ok, i got you wrong, you are wright, the current definitions are correct like that

Actually the typescript definitions are not driven by us, but by the community. If there is a better way to generate it, we are open for it.

**Comment by InExtremaRes** [comment]
Hi, @lppedd 

> The `of()` with > 2 parameters calls `ofNumbers`, which has this signature
> 
> ```
> static ofNumbers(year=0, month=0, dayOfMonth=0, hour=0, minute=0, second=0, nanoOfSecond=0) { ... }
> ```

You're right I didn't remember the defaults of that function, but that signature is wrong either. I mean, if you actually call

```
LocalDateTime.of();
```

it fails at runtime with

```plain
DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
```

That is expected since there is no month or day 0. I agree that the error is not of the declarations.  Date `0000-01-01` is valid but IMO there is no reasonable default date, as opposed to time where `00:00:00` is a very sensible and expected default value. The threeten backport also doesn't seem to allow null values for the date. I you prefer I can open a new issue for that.

I notice the option of using `--allowJs --declaration` although I haven't used yet since all my projects are written in TS. In the meantime I will send a PR to the declarations with some corrections I think they need.
