### ISSUE TITLE
Documentation : Duration manual page typo

### ISSUE THREAD

**Issue by stuboydl** [js-joda/js-joda#350]
approx line 147: "// calculate the durations between **to** time-based temporals"
should be: "// calculate the durations between **two** time-based temporals"

nb. "time-based temporals" is a tautology - the whole line might be better stated as:
"calculate the duration between two temporal values"

**Comment by pithu** [comment]
Hello @stuboydl 

thanks for reporting, we are open for pull requests ;) 

The prefix `time-based` might be important, because threeten distinguish between date-based (Period) and time-based (Duration) durations.

**Comment by stuboydl** [comment]
Hi @pithu 
I've taken the bull by the horns as suggested and updated the type in two places and raised pull requests :)
Cheers

**Comment by pithu** [comment]
thx a lot!
