### ISSUE TITLE
Question: When will there be a new major release and what can be changed?

### ISSUE THREAD

**Issue by InExtremaRes** [js-joda/js-joda#355]
As you know I'm working on improving the TypeScript declarations. While researching in the implementations files and java.time I've found several inconsistencies, not only in types declarations but also between different parts of the codebase and between the library and the ThreeTen API.

Just to name a few:

- `TemporalField` has no abstract methods even when the ThreeTen API has some.
- `IsoFields` has some static instances of class `Field` that extends `TemporalField`, but it has the method `getDisplayName` while `ChronoField` has the method `displayName` instead.
- Every `Temporal` object (I think) should have an `equals` method (like `LocalDate`, `Instant`, etc.) but neither `Temporal` nor `TemporalAccessor` has such abstract method so it is not safe to call `equals` in an abstract `Temporal`.
- This library tries to simulate interfaces with classes, but as I commented in #298 this is not the same. Since JavaScript has only single inheritance you can only extends from one class; the API follows (at some extent) the Interface Segregation Principle and there are cases when there's desirable to "implement" more than one interface, but that doesn't work with classes (at least no without manipulate the prototype chain in some way). The basecode has a lot of `requireInstance` calls for those "abstract classes" what forces users of the library to extends even when there is no behaviour to inherit, preventing them to extend from another, more useful base class.

And there are many more. These issues makes the library difficult to type in TypeScript and a little cumbersome to extends or use in more advanced scenarios.

I'd be very happy to help improving this library, not only with TS types but with patches to the code as well. However I don't understand exactly the vision of the library and the rationale behind some decisions made. I am not always sure if start making some non-trivial changes.

I don't know if there are some other channel to discuss these kinds of topics, but in the meanwhile I'll leave here some questions:

- **When is a major release planned? How much changes can be made?**
- **Is the goal of the library to conform to the ThreeTen API (when it makes sense)?**
- **Can we take away some of the "abstract classes" and simulate interfaces by other means?**
- **Is it OK for me to send a PR making methods names consistent?**

**Comment by pithu** [comment]
> When is a major release planned? How much changes can be made?

No plans, we can release whenever it makes sense or on request. Before a major release its nice to collect some issues.

> Is the goal of the library to conform to the ThreeTen API (when it makes sense)?

Simply yes, in doubt we follow ThreeTen

> Can we take away some of the "abstract classes" and simulate interfaces by other means?

Not sure what you are talking about here, could you give some pseudo code examples ?

> Is it OK for me to send a PR making methods names consistent?

Absolutely, we appreciate any help. If things are not consistent, its simply because we never find some time to clean things up.

**Comment by phueper** [comment]
Hi, 
 i agree with @pithu , some additions

> > When is a major release planned? How much changes can be made?
> 
> No plans, we can release whenever it makes sense or on request. Before a major release its nice to collect some issues.
>
We try to follow semver (https://semver.org/) versioning, so any breaking API change would require a major version increment, but we don't plan ahead, so we are free to release whenever we feel it is appropriate.
 
> > Is the goal of the library to conform to the ThreeTen API (when it makes sense)?
> 
> Simply yes, in doubt we follow ThreeTen
👍 
> 
> > Can we take away some of the "abstract classes" and simulate interfaces by other means?
> 
> Not sure what you are talking about here, could you give some pseudo code examples ?
> 
I agree, we have to keep in mind , that js-joda is (at least from my point of view) first and foremost a JS library, i don't know which changes you would like to make and we are certainly very much open to discuss any, but i'm not sure about changes "just" to make TS happy... i know that TS could make it easier to have some of the interfaces that threeten defines, that we couldn't or didn't define in JS (for the reasons you mentioned) but we still have to keep the non-TS developers in mind :). If TS is "just JS with some enhancements" it should be happy to have "just a JS lib" ;)

> > Is it OK for me to send a PR making methods names consistent?
> 
> Absolutely, we appreciate any help. If things are not consistent, its simply because we never find some time to clean things up.

Absolutely! In the specific case you mentioned (`displayName` vs `getDisplayName`) i seem to remember that during the porting we decided that having get/set functions doesn't feel "natural" in JS so we decided to drop the get/set prefix, but as you mentioned this is not consistent throughout the library and could certainly be cleaned up :) 

Regards, Pattrick

**Comment by InExtremaRes** [comment]
Sorry for the delay but work is getting harder this days. Thank you for your quick replies.

## Regarding the interface issue

You have "pure abstract" classes to simulate interfaces, like `TemporalAdjuster` or `TemporalAmount`, in which every method calls `abstractMethodFail`. There is also some "non pure abstract" classes, like `TemporalAccessor`, that have some concrete methods (I guess) to simulate interfaces with _default implementation_ as Java 8 onwards. Some classes, like `TemporalField` has no declared methods, is just an empty class.

Some classes, like `Instant`, should implement `TemporalAccessor` and `TemporalAdjuster` but now they only _extends_ from `TemporalAccessor` since cannot extends from anything else; I suppose that's why there is no `requireIntance` for `TemporalAdjuster` in the library.

Other classes, like `Period`, should only implement `TemporalAmount` _but extend_ the abstract class `ChronoPeriod` (if there was support to other chronologies). Right now `Period` extends from `TemporalAmount` so it will not be able to extends from `ChronoPeriod` if that feature is added in the future.

Now let's say I want to implement `TemporalField` to create my own _field_ (not an easy task I know, but possible). Due to some `requireInstance` I _have to_ extends `TemporalField`, even when I get no value from it. If I need to create more than one field is very likely I want to create my own abstract base class to put common behaviour, but I will not be able to extend both. The same could happen if I was implementing `TemporalAdjuster` and there was `requireInstance` for that class. And this affects JS and TS users.

## My proposal

This is potentially a long time transition so I split this in steps, some can be delayed.

1. Create some utility that check the _shape_ of an object instead of the constructor. I imagine something like this:
    ```js
    // for internal use only
    const TemporalAdjuster = new Interface({
        adjustInto: 'function',
    });

    // In some class...
    withTemporalAdjuster(adjuster) {
        TemporalAdjuster.assertImplementation(adjuster);
        
        return adjuster.adjustInto(this);
    }
    ```
    `Interface` would be an utility class that will allow to check a given object, throwing an exception if some of the _requirements_ of the interface is not met; in the example an exception is thrown if `adjuster` doesn't have a property `adjustInto` of type `'function'` (checked internally using `typeof` for every property given to `Interface`).
2.  Remove some "abstract" classes that have no behaviour, like `TemporalAdjuster` or `TemporalUnit`, along with its corresponding `requireInstance`. Use instead `Interface` utility to check the _shape_ of the given argument.
    - The only important drawback I can think of is documentation; now you use this classes to give a target to JSDoc and those classes will not exists anymore. I believe JSDoc allows _virtual comments_ ([doc](https://jsdoc.app/tags-interface.html)) so maybe documentation can still be generated. For TS users an `interface` can replace the old class.
3. For "interfaces" with default implementation, like `TemporalAccessor`, separate the interface declaration from implementation, moving behaviour to a new abstract class like `DefaultTemporalAccessor` (as ThreeTen does in absence of _default_ support). The interface declaration will use `Interface` utility to allow checking arguments and internal classes will extend the default class to inherit base behaviour. Those default classes can be exported to users who need them.
4. Default classes can be converted to _mixins_. In JS is valid to extend from a function call if the function returns an extendable function (like a class). This will allow users (and to the library itself) to use the behaviour of the default abstract class without limiting them to extend from another base class. This would look something like this:
    ```js
    // exported from the library
    function DefaultTemporalAccessor(baseClass = Object) {
        return class DefaultTemporalAccessor extends baseClass {
            query(query) { /* ... */ }
            get(field) { /* ... */ }
            range(field) { /* ... */ }
        }
    }

    // user's code
    class ABaseClass {}
    class MyClass extends DefaultTemporalAccessor(ABaseClass) {
        // ...
    }
    ```
    Thus, `MyClass` can extends the default behaviour given by `DefaultTemporalAccesor` and from `ABaseClass` at the same time. If no base class is given then `Object` is used that is the default every time a class have no `extends` clause.
    - This is the most "experimental" step and should be considered carefully. This is valid JS but support from different vendors could vary. I guess Babel could help here, but more research is needed before go this way.
    - Users that need to inherit the default behaviour will be forced to a new syntax, with potentially different semantics than those they're used to; however most users will never implement interfaces themselves and the few that need to usually know what they're doing. The pattern is also not that extraneous and with good documentation it could be feasible to use it. We can always export a direct class to extends from if users doesn't need more than one base class.

I would like to hear your opinions on this. I can open a new issue to track this specific discussion if you're interested.

**Comment by InExtremaRes** [comment]
Some more question regarding the release:

Some of the PR recently merged are safe to use in a minor release. For changes that will be in a major release (new TS declarations, changing of methods names), is it better to send a PR to a different branch instead of master? Or do you reserve master for development of the new major release and open a new branch for bugfixes of the current version?

**Comment by thrucker** [comment]
My two cents on the interface issue:

I think in the end js-joda should use the same interfaces and inheritance as ThreeTen specifies as those are well designed. As @InExtremaRes describes, I see two main points which need to be considered here.

**Allow implementing multiple interfaces in one class.** The idea of using mixins seems to be the way to go. I could imagine something simple like `applyMixins` how typescript suggests: https://www.typescriptlang.org/docs/handbook/mixins.html. This would also naturally allow default implementations for interface methods.

**Asserting and interface on an object.** As @InExtremaRes suggests something simple like a static `assertImplementation` function on each interface seems sufficient. An `assertImplementation` function could be implemented by checking a well known but private property which contains a marker for the specific interface which would be set in `applyMixins`. Or alternatively it could really check if the methods of the interface are present on the object, which would bring some run-time overhead compared to the marker property.

**Comment by pithu** [comment]
> Some of the PR recently merged are safe to use in a minor release. For changes that will be in a major release (new TS declarations, changing of methods names), is it better to send a PR to a different branch instead of master? Or do you reserve master for development of the new major release and open a new branch for bugfixes of the current version?

We have no plans to maintain different branches for minor and major releases. 
The API is stable, we simply implement threeten, so actually we only add functionality. If we have to make major releases, its mostly for clean up typescript definitions or we change a bit how interfaces or imports, etc. are handled. Therefore for a consumer of this API it should be very easy to upgrade to a major version and I see no reason to maintain older major versions.

**Comment by pithu** [comment]
My two cents in the interface issue:

I agree with @phueper, this is an ES6 library,  i'm not sure about changes "just" to make TS happy... 

And of course ES6 comes to the limits, when we try implement java code ... But threeten is an backport for java 6 and 7, so we don't have to think about java 8 here. And ES6 and java can only extend from one class, so i see no major issue here.

And with the interfaces i would prefer any practical solution, that solves our real world problems!

So somehow specifying that a certain class implements an interface is more a theoretical problem for me. Important is, that the class implements that methods and that we can check that. So instead of `requireInstance` we could implement a `requireMethods`. Not sure if we need something like mixins for that.

**Comment by BillSchumacher** [comment]
It would be nice to not have breaking API changes... thanks.
