### ISSUE TITLE
`Temporal` interface is lacking methods

### ISSUE THREAD

**Issue by thrucker** [js-joda/js-joda#360]
The [`Temporal`](https://github.com/js-joda/js-joda/blob/bcc2f3a1cb693b52cb3231787456d4167fbbeca9/packages/core/src/temporal/Temporal.js) interface currently does not define any own methods. In contrast the [ThreeTen/java.time API](https://docs.oracle.com/javase/8/docs/api/java/time/temporal/Temporal.html) specifies methods like `plus`, `minus`, etc.

Without those methods it seems to be impossible to implement for example the `addTo` and `subtractFrom` methods of `TemporalAmount` interface as they need to be able to do a meaningful calculation with the `Temporal` they get.

For example the [implementation of `addTo` in the `Period` class](https://github.com/js-joda/js-joda/blob/bcc2f3a1cb693b52cb3231787456d4167fbbeca9/packages/core/src/Period.js#L792-L807) just uses a `plus` method of the `Temporal` it gets, but according to the defined types this would be a type error.

**Comment by pithu** [comment]
Hello @thrucker, 

can you precise your issue?

I wonder how you can produce a TypeError there with plain javascript. Or are you talking about typescript or flowjs issues ?

**Comment by thrucker** [comment]
Yes, it's a typescript issue and also the corresponding documentation doesn't show the expected methods: https://js-joda.github.io/js-joda/class/packages/core/src/temporal/Temporal.js~Temporal.html.

**Comment by pithu** [comment]
Well, the typescript definitions are community driven, we welcome PR's !

**Comment by pithu** [comment]
And as far as i remember we add something like `abstractMethodFailed` to the javascript "pseudo interfaces" in such cases.

**Comment by thrucker** [comment]
Alright. I'll try to provide a PR.
