### ISSUE TITLE
Feature Request: Support for RFC 1123

### ISSUE THREAD

**Issue by fer22f** [js-joda/js-joda#367]
Because HTTP headers use this in lots of places, I feel the need of a way to format into them. I tried to copy them from Java land:
```java
Map<Long, String> dow = new HashMap(); dow.put(1L, "Mon"); dow.put(2L, "Tue"); dow.put(3L, "Wed"); dow.put(4L, "Thu"); dow.put(5L, "Fri"); dow.put(6L, "Sat"); dow.put(7L, "Sun");
Map<Long, String> moy = new HashMap();
moy.put(1L, "Jan"); moy.put(2L, "Feb"); moy.put(3L, "Mar"); moy.put(4L, "Apr"); moy.put(5L, "May"); moy.put(6L, "Jun"); moy.put(7L, "Jul"); moy.put(8L, "Aug"); moy.put(9L, "Sep"); moy.put(10L, "Oct"); moy.put(11L, "Nov"); moy.put(12L, "Dec");
RFC_1123_DATE_TIME = (new DateTimeFormatterBuilder()).parseCaseInsensitive().parseLenient().optionalStart().appendText(ChronoField.DAY_OF_WEEK, dow).appendLiteral(", ").optionalEnd().appendValue(ChronoField.DAY_OF_MONTH, 1, 2, SignStyle.NOT_NEGATIVE).appendLiteral(' ').appendText(ChronoField.MONTH_OF_YEAR, moy).appendLiteral(' ').appendValue(ChronoField.YEAR, 4).appendLiteral(' ').appendValue(ChronoField.HOUR_OF_DAY, 2).appendLiteral(':').appendValue(ChronoField.MINUTE_OF_HOUR, 2).optionalStart().appendLiteral(':').appendValue(ChronoField.SECOND_OF_MINUTE, 2).optionalEnd().appendLiteral(' ').appendOffset("+HHMM", "GMT").toFormatter(ResolverStyle.SMART).withChronology(IsoChronology.INSTANCE);
```
But didn't have success since we don't have `appendText` with maps implemented.

**Comment by phueper** [comment]
Hi @fer22f thanks for using js-joda and thanks for reporting this issue.

Actually I believe appendText is implemented in the js-joda-locale package to support locale functionality. I never considered being able to use it without locale data, but your sample does make sense. Maybe it is possible to move the appendText implementation from the locale package to core without the locale specific part just for the maps based functionality 🤔

I'll take a look at it 

Regards, Pattrick

**Comment by fer22f** [comment]
Neat!

Yea, I was looking into js-joda-locale and couldn't figure out how to make it work properly, it just ended up throwing me a "DayOfWeek not supported" error and I gave up. My next step is writing this by hand by using the getters, but it would certainly be appreciated if we were able to do something like this just with `core`.

**Comment by phueper** [comment]
Hi @fer22f 

i tried your example and with the following code:

```
const {
  ChronoField,
  DateTimeFormatterBuilder,
    IsoChronology,
  ResolverStyle,
  SignStyle,
  ZonedDateTime,
  ZoneId
} = require('@js-joda/core');
require('@js-joda/timezone');
require('@js-joda/locale_en-us');

const zdt = ZonedDateTime.of(2017, 1, 1, 0, 0, 0, 0, ZoneId.of('Europe/Berlin'));

const dow = {
  1: "Mon",
  2: "Tue",
  3: "Wed",
  4: "Thu",
  5: "Fri",
  6: "Sat",
  7: "Sun",
};
const moy = {
1: "Jan",
2: "Feb",
3: "Mar",
4: "Apr",
5: "May",
6: "Jun",
7: "Jul",
8: "Aug",
9: "Sep",
10: "Oct",
11: "Nov",
12: "Dec",
};
const RFC_1123_DATE_TIME =
    (new DateTimeFormatterBuilder())
        .parseCaseInsensitive()
        .parseLenient()
        .optionalStart()
        .appendText(ChronoField.DAY_OF_WEEK, dow)
        .appendLiteral(", ")
        .optionalEnd()
        .appendValue(ChronoField.DAY_OF_MONTH, 1, 2, SignStyle.NOT_NEGATIVE)
        .appendLiteral(' ')
        .appendText(ChronoField.MONTH_OF_YEAR, moy)
        .appendLiteral(' ')
        .appendValue(ChronoField.YEAR, 4)
        .appendLiteral(' ')
        .appendValue(ChronoField.HOUR_OF_DAY, 2)
        .appendLiteral(':')
        .appendValue(ChronoField.MINUTE_OF_HOUR, 2)
        .optionalStart()
        .appendLiteral(':')
        .appendValue(ChronoField.SECOND_OF_MINUTE, 2)
        .optionalEnd()
        .appendLiteral(' ')
        .appendOffset("+HHMM", "GMT")
        .toFormatter(ResolverStyle.SMART)
        .withChronology(IsoChronology.INSTANCE);

console.log('RFC1123 formatted string:', zdt.format(RFC_1123_DATE_TIME));
```

i get this output:

```
RFC1123 formatted string: Sun, 1 Jan 2017 00:00:00 +0100
```

which looks correct to me ?

This should work right now... but... you need to use a @js-joda/locale_* package, since the appendText function is implemented there ... i discussed with @pithu  about moving it to core, but at least for now we'd rather keep it as it is, i.e. appendText implemented in locale ... we want to keep core really as small as possible  ... 

Thus i will close this issue for now, feel free to reopen if you see it as still being open or would like to discuss it more.

Regards, Pattrick

**Comment by fer22f** [comment]
Yep, I think that works beautifully! Thank you.

**Comment by phueper** [comment]
> Yep, I think that works beautifully! Thank you.
> 
> I know what I was doing wrong: Trying to format `Instant`s, when I should be formatting `ZonedDateTime`s with `ZoneId.of('GMT')` (or equivalent).

Hmmm... Actually... *if* formatting Instants works in threetenbp in Java and doesn't work in js-joda that might be a(nother) bug... :-)

**Comment by fer22f** [comment]
> Hmmm... Actually... if formatting Instants works in threetenbp in Java and doesn't work in js-joda that might be a(nother) bug... :-)

It doesn't, don't worry about that, it crashes as you would expect:

```java.lang.RuntimeException: Unable to create application com.toesgo.app.ToesgoApplication: org.threeten.bp.temporal.UnsupportedTemporalTypeException: Unsupported field: DayOfMonth```

From:
```java
        Log.d("Test", DateTimeFormatter.RFC_1123_DATE_TIME.format(Instant.now()))
```

It's just that I didn't need to do any formatting on the Java code (Android), just parsing.

The error does make sense, `Instant`s shouldn't have any sense of week days!
