### ISSUE TITLE
Needs documentation on Mocking for tests

### ISSUE THREAD

**Issue by mentierd** [js-joda/js-joda#372]
I’ve spent quite some time looking for how to properly mock js-joda in unit/integration tests, but I can’t find anything.  Since this library doesn’t utilize the native date object, you can’t use existing solutions like jest-date-mock or jest-plugin-clock.  

I did come across some comments within the source code about testing within the Clock file; residing on the FixedClock class. 

Would it be possible to add some documentation for how to properly mock LocalDateTime?

**Comment by pithu** [comment]
Hello @mentierd,

i don't quite get your issue, could you provide some pseudo code ? 

If you want to mock the current time, like call of `LocalDateTime.now()` in your application, this is possible with any standard javascript solution, like sinon, etc. Internally js-joda uses `new Date().getTime()` to get the current system time.

**Comment by mentierd** [comment]
@pithu thanks for the quick response. What I was attempting to do was mock the date/time returned from LocalDateTime.now(), so that it will always return the same date/time instance. I'm doing that as part of my unit and integration tests in jest.

Sorry for the confusion, I didn't realize that js-joda is still using Date().getTime() to get the current system time. If that is the case, I should be able to use other existing solutions to mock the native Date object in my jest tests; such as: https://www.npmjs.com/package/jest-plugin-clock

**Comment by pithu** [comment]
So i close the issue for now, feel free to reopen it again if you have further questions
