### ISSUE TITLE
Error while trying to print month name; error message suggests looking into deprecated js-joda-locale package

### ISSUE THREAD

**Issue by thojanssens** [js-joda/js-joda#375]
I can't seem to print a month name:
```
import { DateTimeFormatter } from '@js-joda/core';

const monthFormatter = DateTimeFormatter.ofPattern('MMMM');

yearMonth.atDay(1).format(monthFormatter)
```

Error:
> Pattern using (localized) text not implemented, use js-joda-locale plugin!

Then I go look in the `js-joda-locale` repo as suggested in the error, but it is marked as deprecated... so pretty confused now on the best approach.

**Comment by pithu** [comment]
Please check https://github.com/js-joda/js-joda#js-joda-is-now-a-mono-repo. js-joda is now a mono repo. you find the package in this repository.

**Comment by thojanssens** [comment]
Thank you pithu for answering so fast!

Sorry, can you please explain me how I can print the month name (e.g. January) from a `LocaleDate`? It is not very clear. I checked the package `@js-joda/locale` as you suggested; I see the `LocaleDateTimeFormatter` class, I should use that?

I try to import it:
`import { LocaleDateTimeFormatter } from '@js-joda/locale';`
But doesn't work, my IDE says it is not exported:
> Error: 'LocaleDateTimeFormatter' is not exported by node_modules\@js-joda\locale\dist\js-joda-locale.js

```
import { LocaleDateTimeFormatter } from '@js-joda/locale';

const monthFormatter = LocaleDateTimeFormatter.ofPattern('MMMM');

yearMonth.atDay(1).format(monthFormatter)
```

**Comment by thojanssens** [comment]
Here is my progress, stumbled accross:
https://js-joda.github.io/js-joda/manual/formatting.html
Most of the links are broken links on that page, it needs to be reviewed.

Content needs to be updated I think, I see imports such as:
`import 'js-joda-timezone' `
I think should be: `import '@js-joda/timezone'`
and from `'js-joda'` should be from `'@js-joda/core'`

Anyway followed the guide, now I do:
`import { Locale } from '@js-joda/locale_en`

However I have the error:
> Error: 'Locale' is not exported by node_modules\@js-joda\locale_en\dist\index.js

**Comment by thojanssens** [comment]
Eventually used `Intl`:

`convert(myLocalDate).toDate().toLocaleDateString('en-US', { month: 'long' });`
