### ISSUE TITLE
Warning about incorrect peer dependency

### ISSUE THREAD

**Issue by neuronaut** [js-joda/js-joda#376]
I'm getting the following warning when I install dependencies ever since updating to @js-joda/core 2.x:

`warning " > @js-joda/timezone@2.2.0" has incorrect peer dependency "@js-joda/core@^1.11.0"`

It seems that the peer dependency in @js-joda/timezone needs to be updated. (Or should I not be using @js-joda/timezone 2.x with @js-joda/core 2.x?)

My dependencies in package.json are declared like this:

```
"@js-joda/core": "^2.0.0",
"@js-joda/timezone": "^2.0.0",
```

And my requires in the code are like this:

```
const { ZonedDateTime } = require('@js-code/core');
require('@js-joda/timezone');
```

Is this correct?

**Comment by pithu** [comment]
was already fixed but not yet released
