### ISSUE TITLE
ZonedDateTime doesn't accept timezone designator without colon separator

### ISSUE THREAD

**Issue by fer22f** [js-joda/js-joda#377]
So I'm trying to parse this string outputted by `moment`/`fecha` using specifier `ZZ`: `2020-01-30T15:34:06-0300` and it just won't accept it, while the version with the colon works fine:

```node
> require('@js-joda/core').ZonedDateTime.parse('2020-01-30T15:34:06-0300')
Uncaught:
DateTimeParseException: Text '2020-01-30T15:34:06-0300' could not be parsed at index 19: 2020-01-30T15:34:06-0300, at index: 19
> require('@js-joda/core').ZonedDateTime.parse('2020-01-30T15:34:06-03:00')
ZonedDateTime {
  _dateTime: LocalDateTime {
    _date: LocalDate { _year: 2020, _month: 1, _day: 30 },
    _time: LocalTime { _hour: 15, _minute: 34, _second: 6, _nano: 0 }
  },
  _offset: <ref *1> ZoneOffset {
    _totalSeconds: -10800,
    _rules: Fixed { _offset: [Circular *1] },
    _id: '-03:00'
  },
  _zone: <ref *1> ZoneOffset {
    _totalSeconds: -10800,
    _rules: Fixed { _offset: [Circular *1] },
    _id: '-03:00'
  }
}
```

I don't know if Wikipedia is a reliable source (but I don't have access to ISO 8601:2004 either), but they [do list it as valid](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators):

```
<time>±hhmm
```

**Comment by pithu** [comment]
Hello @fer22f 

js-joda/ threeten and java.time APO comes with built-in parsers/ formatters for ISO 8601 as specified in RFC 3339. see [https://www.ietf.org/rfc/rfc3339.txt](https://www.ietf.org/rfc/rfc3339.txt) `section 5.6. Internet Date/Time Format`

For everything else you have to define custom formatters. examples are found here https://js-joda.github.io/js-joda/manual/formatting.html#format-patterns.

Does this answer your question ?

**Comment by fer22f** [comment]
@pithu It does, since RFC3339's is only a profile of ISO 8601, and it requires a colon there:

```
   time-hour       = 2DIGIT  ; 00-23
   time-minute     = 2DIGIT  ; 00-59
   time-numoffset  = ("+" / "-") time-hour ":" time-minute
   time-offset     = "Z" / time-numoffset
```

I'm opening an issue in the project that I'm using to format, thanks!
