### ISSUE TITLE
Certain numbers yield a zero length period when they shouldn't

### ISSUE THREAD

**Issue by bowersj** [js-joda/js-joda#378]
Hi Joda supporters! Thanks for porting Joda to JavaScript.

First of all, sorry for closing the issue prematurely, this is my first one.

### The Problem
This specific problem is one where if you use the `Period.ofDays()` method certain numbers return a period of length 0.  From basic tests it seems that the problematic numbers are 4294967296 and 8589934592 which, 8589934592 is just 4294967296 * 2. I understand that  4294967296 is a huge number of days so this is definitely an edge case but I thought that you would like to know of this potential problem.

### The Cause
This seems to stem from the line `if((_years | _months | _days) === 0)`. I believe the problem is the use of a bitwise OR here ( `|` ). 

### The Solution
It can also be fixed quite simply by switching the `|` to `||`. This might have performance implications so there is possibly a better solution.

By the way, I've been testing Joda in extreme cases lately and it is proving itself to be quite robust, thanks for all the hard work!

**Comment by phueper** [comment]
Hi @bowersj,

Thanks for reporting and thanks for using js-joda. Indeed the bitwise or operator seems to be wrong. Would you mind creating a PR with the fix? Then we can merge and close this issue.

Regards, Pattrick

**Comment by phueper** [comment]
Funnily enough, our base, the threetenbp indeed has a bitwise or as well https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/Period.java#L348, however the behavior might be a different in Java due to the size of int 🤔

**Comment by phueper** [comment]
I guess we would have to check the behavior in threetenbp as well

**Comment by phueper** [comment]
I think I understand what happens... According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators  the bitwise operators only operate on the lower 32 bits... Since your number of days in binary has the lowest 32 bits not set (the same for multiplication with 2 naturally) the bitwise or equals 0...i would guess this is different in Java... Anyway probably checking that all three fields are 0 in the condition might be slightly slower but makes more sense...

**Comment by bowersj** [comment]
Thanks for your quick response! Your explanation makes sense and I agree that checking for 0 makes more sense than using the bitwise or. I'll get working on a pull request when I get a minute.

**Comment by bowersj** [comment]
I created a [Pull Request] (https://github.com/js-joda/js-joda/pull/379). Let me know if there are any concerns.

**Comment by phueper** [comment]
PR is merged I'll close this issue
