### ISSUE TITLE
Long timezone formatting for GMT

### ISSUE THREAD

**Issue by jonfreedman** [js-joda/js-joda#380]
The second expect in this test fails as the output is `Mon Feb 05 2018 00:00:00 GMT+0000 (GMT)`, is there a way to make this pass?

```javascript
import { DateTimeFormatter, LocalDate, ZonedDateTime, ZoneId } from '@js-joda/core';
import { Locale } from '@js-joda/locale_en';
require('@js-joda/timezone');

describe('DateParser', () => {
    it('format', () => {
        const formatter = DateTimeFormatter.ofPattern('EEE MMM dd yyyy HH:mm:ss \'GMT\'Z (zzzz)').withLocale(Locale.UK);
        expect(LocalDate.of(2018, 2, 5).atStartOfDay().atZone(ZoneId.of('America/New_York')).format(formatter)).toEqual('Mon Feb 05 2018 00:00:00 GMT-0500 (Eastern Time)');
        expect(LocalDate.of(2018, 2, 5).atStartOfDay().atZone(ZoneId.of('GMT')).format(formatter)).toEqual('Mon Feb 05 2018 00:00:00 GMT+0000 (Greenwich Mean Time)');
    });
});
```
The equivalent test in Java suggests perhaps zzzz is being mapped incorrectly?
```java
import org.junit.Test;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

import static org.assertj.core.api.Assertions.assertThat;

public class TestDateParser {
    @Test
    public void format() {
        final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEE MMM dd yyyy HH:mm:ss 'GMT'Z (zzzz)");
        assertThat(ZonedDateTime.of(LocalDate.of(2018, 2, 5), LocalTime.MIDNIGHT, ZoneId.of("America/New_York")).format(formatter)).isEqualTo("Mon Feb 05 2018 00:00:00 GMT-0500 (Eastern Standard Time)");
        assertThat(ZonedDateTime.of(LocalDate.of(2018, 2, 5), LocalTime.MIDNIGHT, ZoneId.of("GMT")).format(formatter)).isEqualTo("Mon Feb 05 2018 00:00:00 GMT+0000 (Greenwich Mean Time)");
    }
}
```
Note `Eastern Time` vs `Eastern Standard Time` as well as `GMT` vs `Greenwich Mean Time`

**Comment by jonfreedman** [comment]
It looks like [CldrDateTimeFormatterBuilder](https://github.com/js-joda/js-joda/blob/master/packages/locale/src/format/cldr/CldrDateTimeFormatterBuilder.js#L182) constructs a [CldrZoneTextPrinterParser](https://github.com/js-joda/js-joda/blob/master/packages/locale/src/format/cldr/CldrZoneTextPrinterParser.js) with `TextStyle.FULL` via [DateTimeFormatterBuilder](https://github.com/js-joda/js-joda/blob/master/packages/core/src/format/DateTimeFormatterBuilder.js#L894) but beyond that I'm a bit lost.

I have cldr-data\main\en\timeZoneNames.json which contains
```json
            "GMT": {
              "long": {
                "standard": "Greenwich Mean Time"
              },
              "short": {
                "standard": "GMT"
              }
            },
```

**Comment by phueper** [comment]
@jonfreedman it might be due to cldr data not completely matching the data from Java... Or the FULL mapping not working correctly... I'll try to take a look and see if I can find out what's going wrong

**Comment by phueper** [comment]
Strange... this test:

https://github.com/js-joda/js-joda/blob/master/packages/locale/test/format/ZoneTextPrinterParserTest.js#L45

seems to indicate that TextStyle.FULL *is* being mapped to "Greenwich Mean Time" as it should :thinking:

**Comment by jonfreedman** [comment]
Yes so looks like the wiring up of DateTimeFormatter must be broken, perhaps you can lift that test code to cover this issue as well

**Comment by phueper** [comment]
I will try to 👍

**Comment by phueper** [comment]
Hi @jonfreedman ,

i tried to debug the issue: my findings:

- i translated the test to Java, but instead of testing java.time, i tested with threetenbp (which is our base project after all) 

```
package org.threeten.bp.format;

import org.testng.annotations.Test;
import org.threeten.bp.LocalDate;
import org.threeten.bp.LocalTime;
import org.threeten.bp.ZoneId;
import org.threeten.bp.ZonedDateTime;

import static org.testng.Assert.assertEquals;

public class TestDateTimeFormatterIssue380
{
    @Test
    public void format()
    {
        final DateTimeFormatter formatter = DateTimeFormatter.ofPattern(
                "EEE MMM dd yyyy HH:mm:ss 'GMT'Z (zzzz)");
        assertEquals(ZonedDateTime.of(LocalDate.of(2018, 2, 5),
                                      LocalTime.MIDNIGHT,
                                      ZoneId.of("America/New_York")).format(formatter),
                     "Mon Feb 05 2018 00:00:00 GMT-0500 (Eastern Standard Time)");
        assertEquals(ZonedDateTime.of(LocalDate.of(2018, 2, 5),
                                      LocalTime.MIDNIGHT,
                                      ZoneId.of("GMT")).format(formatter),
                     "Mon Feb 05 2018 00:00:00 GMT+0000 (Greenwich Mean Time)");
    }
}
```

And i do get the same Test Failure (it prints GMT instead of Greenwich Mean Time) ...

The reason is this check: https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/format/DateTimeFormatterBuilder.java#L3366  and in js-joda: https://github.com/js-joda/js-joda/blob/master/packages/locale/src/format/cldr/CldrZoneTextPrinterParser.js#L93

if the Zone we want to print normalizes to a fixed offset (and GMT is a Fixed Offset Zone with offset 0, i guess) we will print the zone Id and not the Zone name. I am not absolutely sure wether that behavior is really expected, but it is consistent between threetenbp and js-joda, and as long as it is, i think we won't change it. 

So... i close this issue for now, feel free to reopen to duscuss this further.

Regards, Pattrick

**Comment by jonfreedman** [comment]
Fair enough although I assume you are aware of the joda -> three ten -> java8 evolution so perhaps the baseline should be updated?

**Comment by phueper** [comment]
Hi, 

Yes we are aware of the evolution. 
But we chose threetenbp for licensing reasons as we try to explain here https://github.com/js-joda/js-joda/blob/master/packages/core/README.md#license

The behavior of the threetenbp is actually very similar to the java.time behavior afaik... Maybe it would be a good idea to ask for the reason why java and threetenbp behave differently in this case in the threetenbp repository.

**Comment by jonfreedman** [comment]
@jodastephen - any idea about this long format timezone diff between threetenbp and the jre?

**Comment by phueper** [comment]
quick check in the jdk Source code ... 
https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/time/format/DateTimeFormatterBuilder.java#l3667

seems to be, that the difference is, that in jdk the normalization is not done... maybe that leads to the difference in results 🤔

**Comment by jonfreedman** [comment]
Maybe Stephen will have a view on this but personally I think the long format for GMT should be "Greenwich Mean Time" not "GMT".

**Comment by phueper** [comment]
i tend to agree with you, but as i said, as long as threetenbp behaves this way, i really don't want to change it in js-joda ...

**Comment by jodastephen** [comment]
I don't have any specific recollection of this. However, threetenbp is supposed to match java.time.* in terms of behaviour weherever possible (when running on the same JDK). If that isn't the case, a PR can be raised in threetenbp, providing you aren't copying the GPL licensed code. ie. it needs to be "clean room" code, which probably rules out everyone on this thread...
