### ISSUE TITLE
Issue with Typescript/Flow types : minusTemporalAmount & plusTemporalAmount

### ISSUE THREAD

**Issue by jonfreedman** [js-joda/js-joda#381]
The type definitions still contain minusTemporalAmount & plusTemporalAmount functions but they seem to have been removed as part of the migration into the js-joda npm org

**Comment by dgreene1** [comment]
I'd be happy to make this change if the maintainers are willing to accept a PR.

**Comment by phueper** [comment]
Hi @dgreene1 ,

We are always happy about PRs

Regards, Pattrick
