### ISSUE TITLE
typescript typings for Duration ofSeconds

### ISSUE THREAD

**Issue by jseter** [js-joda/js-joda#382]
Documentation and code represent this static method as:

public static | ofSeconds(seconds: Number, nanoAdjustment: Number): Duration

however typescript typing file is:
static ofSeconds(seconds: number): Duration;
instead of:
static ofSeconds(seconds: number, nanoAdjustment?: number): Duration;

**Comment by pithu** [comment]
Hello @jseter 

thanks for reporting. The typescript definitions are community driven. We are open for pull requests.
