### ISSUE TITLE
TypeScript declaration types for locales

### ISSUE THREAD

**Issue by InExtremaRes** [js-joda/js-joda#386]
I started working in TS declarations for the locale package but have some questions:

1. Where should I put the file? In core and others the `.d.ts` is in the `dist` folder, but `locale` has many prebuilt packages and every one of them should have an `index.d.ts`. I guess in your infrastructure is possible to copy the same file to every locale specific package at build or package time, however this leads me to the next question.
2. Should every locale specific package have types for its own constants? I mean, if I import `'@js-joda/locale_en-us'` then I have the constants `Locale.US`, `Locale.ENGLISH`, but `Locale.FRENCH` will fail at runtime. Do you think is worthwhile to have independents types declarations for just the constants in every locale specific package?
3. I think the method `DateTimeFormatter.prototype.withLocale(locale)` should not be typed in core and be available only from the moment one imports one locale. This can be done with module augmentation in TypeScript. Is it OK for you? I think that would be a breaking change from the types perspective even though `withLocale` is useless without a proper `Locale` instance. If we can go that path then I suggest to delete the `Locale` interface in core, that is just a hack and allows to pass anything as a Locale (since `Locale` is an empty interface and in TS almost everything is assignable to `{}`).

Regards and good day.

**Comment by phueper** [comment]
Hi @InExtremaRes,

thanks for working on this. My thoughts:

1. I would propose to first of all create a PR that puts a valid .d.ts file in packages/locale/dist . the prebuilt packages are all auto generated, so it doesn't make much sense putting anything in their dist folder... for the other files we use something like templates, or replace values from other files... if you could provide the diff you would imagine from the main d.ts to the locale specific d.ts we can maybe work it out... but as i said, first step would be the file in packages/locale/dist i think

2. i'm not sure wether thats possible... i think we are currently filling an availableLocales field when building the locale specific packages, but i'm not sure wether it is easily possible for the predefines ... for now i would just put all the predefined Locale in the .d.ts (they are available in JS anyway)

3. REgarding this i'm really unsure ... i would also like to get @pithu  s oppinion wether we want to split the .d.ts like this ... i think best would be to have a separate PR for it and discuss it there, i'm not a typescript expert, maybe the implications will become more obvious in a separate PR 🤔

**Comment by pithu** [comment]
I would prefer to keep things simple. What typescript declarations should go to the locale package ? Can't we put these into core ?

**Comment by InExtremaRes** [comment]
Hi @phueper, @pithu.

First of all I want to remark that you don't need to use TypeScript to be using TypeScript (:thinking:); if you use a TS backed editor, like vscode, then you are using TS nonetheless. People working in JS in IDEs/editors like that are largely benefit from intellisense and type checking, and they have to do nothing, just using a library with types declaration. If those types are more precise they definitely help people work better code.

I agree it would be better to start with a single, unified `.d.ts` file with every predefined locale as a property, just like in JS. Having said that, it is possible to have types just for the predefined properties of the _used locales_ instead of an static set that could not be available, is not that hard but dependant on your build system.

The rest of my proposal is this:

1. Remove the `Locale` interface from core. As I said, the empty interface allows me to do `DateTimeFormatter.ofPattern('MMMM').withLocale(123)` without a warning.
2. Remove the types from any locale specific method, like `DateTimeFormatter.prototype.withLocale()`. This methods are useless without a locale installed.
3. Make types for the locale package such that, the first time I import a `'@js-joda/locale_<locale>'` package, TS _augment_ the declaration of `DateTimeFormatter.prototype` and `DateTimeFormatterBuilder.prototype`, adding the methods `withLocale`, `appendText`, etc., just like you do in JS. This is really very easy to do since TS is designed to express the fact that a module can add properties to objects of another module.

I can send a PR during this week so you can see exactly what I mean and discuss the implementation there.

**Comment by InExtremaRes** [comment]
I think this issue is resolved by #389 so I'll close it by now.
