### ISSUE TITLE
Performance degraded when printing timezones

### ISSUE THREAD

**Issue by JKillian** [js-joda/js-joda#394]
Love js-joda, such a great way to work with dates and times in JS, but noticed today some very laggy performance in a table I had where I was using `js-joda` to display some datetimes in a `dd-MMM-yyyy h:MM a z` format. Delving in to the performance issues, the biggest issues were coming from locales calling `Cldr.load` every time I printed a datetime with a timezone name.  See below for full details, but adding in a timezone name makes things around the magnitude of 100x slower:

**Benchmark Code:**
```js
(global as any).testSpeed = () => {
  const NUM_TIMES = 1000;

  const formatterWithoutTimezone = DateTimeFormatter.ofPattern('dd-MMM-yyyy h:MM a').withLocale(Locale.US);
  const formatterWithTimezone = DateTimeFormatter.ofPattern('dd-MMM-yyyy h:MM a z').withLocale(Locale.US);

  const utcDateTime = ZonedDateTime.of(LocalDateTime.of(2020, 1, 2, 4, 5, 6), ZoneId.UTC);
  const nycDateTime = ZonedDateTime.of(LocalDateTime.of(2020, 1, 2, 4, 5, 6), ZoneId.of('America/New_York'));

  console.time('UTC without timezone');
  for (let i = 0; i < NUM_TIMES; ++i) {
    utcDateTime.format(formatterWithoutTimezone);
  }
  console.timeEnd('UTC without timezone');

  console.time('UTC with timezone');
  for (let i = 0; i < NUM_TIMES; ++i) {
    utcDateTime.format(formatterWithTimezone);
  }
  console.timeEnd('UTC with timezone');

  console.time('NYC without timezone');
  for (let i = 0; i < NUM_TIMES; ++i) {
    nycDateTime.format(formatterWithoutTimezone);
  }
  console.timeEnd('NYC without timezone');

  console.time('NYC with timezone');
  for (let i = 0; i < NUM_TIMES; ++i) {
    nycDateTime.format(formatterWithTimezone);
  }
  console.timeEnd('NYC with timezone');
}
```

**Results**:
```
UTC without timezone: 19.212158203125ms (probably just slower because of a cache warming thing being first)
UTC with timezone: 11.41796875ms
NYC without timezone: 5.911865234375ms
NYC with timezone: 599.635009765625ms
```

**Analysis**:
Luckily, it's pretty easy to profile and see where the time is being eaten up, and it's in the locale's `CldrZoneTextPrinterParser.js` `print` function (bottom-up view):

![image](https://user-images.githubusercontent.com/1400151/78306804-45da0a80-7512-11ea-811f-ad52f3dd6fbb.png)

Specifically, the call to `Cldr.load` is the biggest culprit:

https://github.com/js-joda/js-joda/blob/ff6785aa3d13f637544e78c59334662833c4d861/packages/locale/src/format/cldr/CldrZoneTextPrinterParser.js#L108

**Solution?**
Could this call be cached somehow so that it only has to happen the first time something is printed? This same perf issue may be happening in other situations also, as I do see the same calls being made in a locale's in the `CldrZoneTextPrinterParser.js`  `parse` function also.

**Comment by pithu** [comment]
Hi @JKillian thanks for the detailed analysis. There is some lazy caching in the timezone implementation itself, but obviously not in the localisation. Probably some lazy caching could improve the performance, since we have a unique key `main/${context.locale().localeString()}/timeZoneNames.json`)it shouldn't be that complicated. 

We are open for PR's on that
