### ISSUE TITLE
to/from Date

### ISSUE THREAD

**Issue by xenoterracide** [js-joda/js-joda#398]
sometimes, because of other libraries (like TypeOrm) it's hard to get away from the `Date` class. It would be nice to have a converter library for any of the types, but at the very least since java's `Date.from` can't be added `Instant.from(Date)` and `Instant.toDate()`.

**Comment by InExtremaRes** [comment]
Hi. Maybe this issue can be of interest to you: #122.
There is also a [nativeJs](https://js-joda.github.io/js-joda/function/index.html#static-function-nativeJs) function that I think is meant to be of public use.

**Comment by pithu** [comment]
I close this for now, looks like its solved. Feel free to reopen it again
