### ISSUE TITLE
Instant.parse without seconds failes.

### ISSUE THREAD

**Issue by kattn** [js-joda/js-joda#399]
Instant does not parse ISO strings correctly. When parsing the following: 

`Instant.parse("2018-10-15T00:00Z")`

The following exception is thrown: 

> DateTimeParseException: Text '2018-10-15T00:00Z' could not be parsed at index 16: 2018-10-15T00:00Z, at index: 16

JSFiddle example: https://jsfiddle.net/fygpsxkL/

I expect it to parse the string without any issues as ZonedDateTime.parse handles it, so my current fix is to use that.

**Comment by pithu** [comment]
You have to add at least the seconds to the String. 

`Instant.parse("2018-10-15T00:00:00Z")` should work.

**Comment by VsevolodGolovanov** [comment]
It fails even with seconds for me:

    Unhandled Rejection (DateTimeParseException): Text '2008-12-31T21:00:00Z' could not be parsed: : 2008-12-31T21:00:00Z, at index: 0

Seems like it requires milliseconds too.

**Comment by kattn** [comment]
Sorry I was under the impression that Instant.parse could parse a ISO 8601 string, and therefore opened the issue thinking it was a bug. I notice now that never stated so in the documentation:
> Instant is an instantaneous point on the time-line measured from the epoch of 1970-01-01T00:00:00Z in epoch-seconds and nanosecond-of-second.
