### ISSUE TITLE
Proposal: Replace uncommon exception types with standard JS ones

### ISSUE THREAD

**Issue by InExtremaRes** [js-joda/js-joda#414]
Some of the exceptions thrown by js-joda are standard in Java but not in JS, such as `NullPointerException` or `IllegalArgumentException`. For this cases most libraries and environments throw an instance of `TypeError` instead.

So this is my proposal:

- Replace `ArithmeticException` with `RangeError`.
- Replace `NullPointerException` with `TypeError`.
- Replace `IllegalArgumentException` with `TypeError`. If necessary, keep the class but derive it from `TypeError`.

I'm not aware of an standard equivalent for `IllegalStateException`.

The case for `UnsupportedTemporalTypeException`, while in one hand looks to me like a classic case for `TypeError`, on the other I see it's very domain specific and then seems ok to be derived from `DateTimeException`. `DateTimeParseException` should probably derive from `DateTimeException` for a similar reason.

What are your thoughts on this?

**Comment by pithu** [comment]
I don't see the benefit of it. For me the custom errors are part of the threeten API. Without any good reason, i wouldn't change it. 
@phueper what's your opinion on this ?

**Comment by phueper** [comment]
i agree with @pithu  ... even though other errors are mir common in JS, the Exceptions seem to be part of the threeten API to me... i'm not sure, can we somehow extend the threeten exceptions from the JS Errors? so both would work? :thinking:

**Comment by InExtremaRes** [comment]
I agree that this is not a big issue an doesn't affect much. I also see _custom_ errors as part of an API, however I disagree that `ArithmeticException` or `NullPointerException` are _custom_ or part of this domain. `NullPointerException`, for instance, is just a byproduct of the decision made in Java that `null` would be silently assignable to any object (until dereferencing it, of course), is a language-based exception. In JS the same kind of thoughts molded the language; true, it's a dynamic, weakly typed language, but `typeof null == 'object'` which is a big reminiscent of those ideas. But JS has it's own "standard" way of deal with that: `TypeError`. The ThreeTen throws `NullPointerException`s only because it's written in and for Java.

In my particular case, we have a project were any `TypeError` follows a different path of error handling since those should never occur, and when they do, the app scream loud and clear (and dies in shame). But I have to do a "case" specifically for js-joda since it throws its own exceptions. I mentioned this mostly as an example, it is far from being a terrible thing doing a branch-case there.

Derive some of those classes from the standard ones, as @phueper suggested, is a way of doing it. I was thinking in that before opening this, but it's not straightforward when you are targeting less than ES6 though a transpiler. Besides, my main goal here was to present a different POV, to discuss and know your thoughts; I know both of you have very strong opinions.

I'd like you to think about this a little more. If your opinions are the same I can make a PR to see how well goes making some of those classes inherit the prototype of `TypeError`.
