### ISSUE TITLE
Applying bitwise OR to number parameters truncates them to int

### ISSUE THREAD

**Issue by ilya-g** [js-joda/js-joda#431]
Similarly to the issue #378 there are several places in js-joda code base where number parameters are OR'ed together and the result is compared to zero, some examples are:
- https://github.com/js-joda/js-joda/blob/%40js-joda/core%403.0.0/packages/core/src/LocalDateTime.js#L1235
- https://github.com/js-joda/js-joda/blob/%40js-joda/core%403.0.0/packages/core/src/Instant.js#L627

In JS, bitwise OR operator truncates its arguments to 32-bit ints leaving only 32 least significant bits of a number. Therefore, if arguments all have their lowest 32 bits zero, js-joda consider them zero even if they are not equal to it.

This leads to the following incorrect behavior:
`Instant.EPOCH.plusNanos(Math.pow(2, 32))`
Expected to get an instant that is 4.294967296 seconds later than `Instant.EPOCH`.
Actual: getting the same `Instant.EPOCH` instead.

**Comment by pithu** [comment]
very good catch, thanks a lot for reporting !!!! 

I will try to fix it asap
