### ISSUE TITLE
Support Year

### ISSUE THREAD

**Issue by xenoterracide** [js-joda/js-joda#434]
https://docs.oracle.com/javase/8/docs/api/java/time/Year.html

**Comment by pithu** [comment]
Hi @xenoterracide,

thanks for using js-joda, sorry but i don't get your point. Year is already supported see https://js-joda.github.io/js-joda/class/packages/core/src/Year.js~Year.html

I close this pr for now, please feel free to reopen it again, if you have any further questions.
