### ISSUE TITLE
OffsetDateTime and OffsetTime missing in typescript definitions

### ISSUE THREAD

**Issue by pithu** [js-joda/js-joda#440]
OffsetDateTime and OffsetTime, recently added in @js-joda/core@3.0.0 are still missing in the typescript definition files.

Thanks to @xenoterracide, reported this at #432

**Comment by jonfreedman** [comment]
Any chance this can be fixed? I think it would be pretty trivial to do...

**Comment by jonfreedman** [comment]
I've started on this in a fork

**Comment by jonfreedman** [comment]
A merge and release would be appreciated if that's feasible
