### ISSUE TITLE
Implement DateTimeFormatter.withZone

### ISSUE THREAD

**Issue by pauldraper** [js-joda/js-joda#441]
I have a format with an optional time zone. `DateTImeFormatter.withZone` allows the selection of a default zone.

Currently, there is no good way to parse a datetime with optional zone.

**Comment by phueper** [comment]
Hi @pauldraper 

there is a possibility to specify optional sections for Formatters, see https://js-joda.github.io/js-joda/class/packages/core/src/format/DateTimeFormatter.js~DateTimeFormatter.html 

Using this it should be possible to specify a pattern that parses datetime with optional zone i think.

Regards, Pattrick

**Comment by phueper** [comment]
i'll close this for now, feel free to reopen if needed

**Comment by alamothe** [comment]
One other case for `withZone` is to be able to format `Instant`s without converting them to `ZonedDateTime`. 

Is there some specific difficulty in implementing `withZone`?

Thanks!

**Comment by pithu** [comment]
Hello @alamothe, that is by concept. 

An Instant is a point in the timeline -> https://js-joda.github.io/js-joda/class/packages/core/src/Instant.js~Instant.html. 

Adding a certain Zone makes it a ZonedDateTime. Hope that helps.

**Comment by alamothe** [comment]
Understood, however in Java we can format instants as long as the formatter has the zone associated with it:
```kt
val dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd h:mm a").withZone(ZoneId.of("America/New_York"))
val now = Instant.now()
dtf.format(now)
```
and the formatter will automatically convert the instant.

Sometimes this is pretty convenient e.g. there is a single timezone setting on the client and it receives a lot of `Instant`s from the server, it avoids having to convert them all the time.

**Comment by pithu** [comment]
I am not sure why this is not yet implemented. Because it seems to be more or less just syntactic sugar, i guess it can't be difficult to implement. As always, we are open for PR's that complete threeten API.
