### ISSUE TITLE
ES5 compatibility issues

### ISSUE THREAD

**Issue by scottlowe** [js-joda/js-joda#452]
Hi there. Assuming that js-joda still intends to remain ES5 compatible, there is a call to `Array.includes` here:

https://github.com/js-joda/js-joda/blob/a1a635a7e4e506dfa7a9eedcc932571bdba9c1b2/packages/locale/src/format/cldr/CldrDateTimeTextProvider.js#L226

... which breaks compatibility with ES5 browsers (in my case IE11).

There is also a call to `Object.values` somewhere that is causing the same ES5 issue elsewhere in the code; I think that it might be this line:

https://github.com/js-joda/js-joda/blob/e663b249e2987784b60ebb22054d685ad13ed443/packages/locale/src/format/LocaleStore.js#L54

**Comment by pithu** [comment]
Hi @scottlowe,

thanks for using js-joda and reporting this issue !

since we promised to be compatible with ie9, i will fix it. Unfortunately we had to disable ie test on travis for some reasons, therefore issues like that can sneak in.

**Comment by scottlowe** [comment]
Woo! 😄
