### ISSUE TITLE
Question: Is the license relevant to the API or only the implementation?

### ISSUE THREAD

**Issue by InExtremaRes** [js-joda/js-joda#458]
I think I understand the reasons behind this project being a port of the threetenbp and not java.time in the JDK (BSD vs GPL). But, what if I want to implement a new method that is available in java.time and not in threetenbp? Can I take the API but implementing it in my own without problems?

Let's take a concrete example. In Java 8 there is a new method [TemporalAdjusters.ofDateAdjuster](https://docs.oracle.com/javase/8/docs/api/java/time/temporal/TemporalAdjusters.html#ofDateAdjuster-java.util.function.UnaryOperator-) that is not currently part of the threetenbp. Suppose I want to implement that method in js-joda, the names and signature will be mostly the same (adapted to javascript), but the implementation would be brand new (in fact I've never seen the JDK source code). Is that OK from a license perspective?

I think is OK, I've read Stephen ([example](https://github.com/js-joda/js-joda/issues/380#issuecomment-596266169), [example](https://github.com/ThreeTen/threetenbp/issues/76#issuecomment-329790867)) saying that if the implementation is new the changes can be backported to threetenbp (and I guess that's the reason we have methods like `LocalDate.ofInstant`), but I preferred to ask to be sure.

**Comment by pithu** [comment]
That is also my understanding, simply never look at the openjdk source code!
