### ISSUE TITLE
Change ZonedDateTime.toJson to output ISO-8601

### ISSUE THREAD

**Issue by xenoterracide** [js-joda/js-joda#459]
it would be nice if ZonedDateTime could auto serialize to a valid ISO 8601 so that other clients not using js-joda could simply use `Date`, this is also important because of nested objects, and most people simply use `JSON.stringify` instead of some mapper that can provide a callback to how it should be serialized if encountered.

note: if there are any others that don't use the ISO 8601 format, it'd be appreciated if they did this too. I realize this may require a major version increment.

**Comment by pithu** [comment]
As far as i know, there is no equivalent ISO 8601 representation for the zone part (eg `Europe/Paris`) of a ZonedDateTime. If we omit that part in the json representation, the operation is not reversible. 

IMO having a complete json representation of the instance is more important than being compatible to other packages. 
And there is always the possibility to use a mapper for json stringify, so i am closing this Issue for now. Feel free to reopen the issue again, if you have further questions or remarks.
