### ISSUE TITLE
strange behavior when setting WEEK_OF_WEEK_BASED_YEAR depending on year

### ISSUE THREAD

**Issue by mxab** [js-joda/js-joda#464]
I want to set the date by week therefore I do:

```
LocalDate.of(2021, 1,1)
.with(IsoFields.WEEK_OF_WEEK_BASED_YEAR, 4)
```
result is something like: `2020-01-24` for year 2021 

for 2025 is looks better:

```
LocalDate.of(2025, 1,1)
.with(IsoFields.WEEK_OF_WEEK_BASED_YEAR, 4)
```
the result is
`2025-01-22`

Not sure if this is a bug or I just use the API wrong

**Comment by phueper** [comment]
Hi @mxab,

first of all thanks for using js-joda and thanks for reporting.

i think the behavior is correct 2021-01-01 is in week *53* of week based year 202*0* ... so week 4 of the week based year 202*0* is 2020-01-24 ... to be sure the get the week 4 of 2021 i believe you should use a date that surely is in a week of the year 2021, e.g. 2021-01-10.

see e.g. http://www.whatweekisit.org/calendar-2021.html

while in 2025 ... the first of January is actually in week 1 of 2025 http://www.whatweekisit.org/calendar-2025.html

I hope this helps, i will close this issue, feel free to reopen if you have further questions

Regards, Pattrick

**Comment by mxab** [comment]
@phueper thanks for your fast response and thank you in general for jodatime js :)

I guess the explanation makes sense

Could you give me a hint tough how to create a LocalDate for a certain day of a given calendar week and year
e.g.:
year 2021, week: 1, monday -> 2021-01-04
year 2020, week: 1, monday -> 2019-01-30

**Comment by phueper** [comment]
@mxab i would propose using LocalDate.withFieldValue, see https://js-joda.github.io/js-joda/class/packages/core/src/LocalDate.js~LocalDate.html#instance-method-withFieldValue

that can also be chained ..

**Comment by phueper** [comment]
reading my comment I think it is misleading... you still use. .with() but with one of the ChronoField s mentioned in the above description... I hope that makes it clearer?

**Comment by mxab** [comment]
hmm still struggling

```
LocalDate.of(2020,1,1)
 .with(ChronoField.ALIGNED_WEEK_OF_YEAR,1)
 .with(ChronoField.DAY_OF_WEEK, DayOfWeek.MONDAY.value())
```
points now `2019-12-30` which is correct
but 
```
LocalDate.of(2021,1,1)
 .with(ChronoField.ALIGNED_WEEK_OF_YEAR,1)
 .with(ChronoField.DAY_OF_WEEK, DayOfWeek.MONDAY.value())
```
point to `2020-12-28` but it should be `2021-01-04`

Also I'm not sure if setting monday like this directly or if I can set somewhere the I can set the general setting what the first day of the week is (monday in my case) and then tell it to go to the first day of a calendar week
