### ISSUE TITLE
Difference between two ZonedDateTime

### ISSUE THREAD

**Issue by Pavel-Husakouski** [js-joda/js-joda#470]
I'm trying to implement the difference between the dates 
```
ZonedDateTime.now().minus(ZonedDateTime.parse('2016-03-18T17:00+01:00'))
ZonedDateTime.now().until(ZonedDateTime.parse('2016-03-18T17:00+01:00'))
```
Both throw an exception.
Is there a support of such opperations?

**Comment by aukevanleeuwen** [comment]
Not exactly sure what you were expecting to get back out of this to be honest, but it feels like you should use either [`Period`](https://js-joda.github.io/js-joda/class/packages/core/src/Period.js~Period.html) or [`Duration`](https://js-joda.github.io/js-joda/class/packages/core/src/Duration.js~Duration.html) for this:

```javascript
❯ node
Welcome to Node.js v12.20.1.
Type ".help" for more information.
> const { Duration, ZonedDateTime } = require('@js-joda/core');
undefined
> const past = ZonedDateTime.parse('2016-03-18T17:00+01:00');
undefined
> const now = ZonedDateTime.now();
undefined
> const duration = Duration.between(past, now);
undefined
> duration.seconds();
155259750
> duration.toHours()
43127
> duration.toMillis()
155259750756
```

**Comment by InExtremaRes** [comment]
Just to expand a little to what @aukevanleeuwen said:

The `minus` method on a `Temporal` expects a `TemporalAmount` or a value and unit, and returns another `Temporal` (`ZonedDateTime` in your example). Typical implementations of `TemporalAmount` are `Duration` or `Period`. So you can do this:

```js
const t1 = ZonedDateTime.parse("2016-03-18T17:00+01:00");
const oneDay = Period.ofDays(1);

const r = t1.minus(oneDay);
console.log(r.toString());
// -> "2016-03-17T17:00+01:00"
```

The method `until` does return the amount of time between two `Temporal` objects but you have to specify the unit:

```js
const t1 = ZonedDateTime.parse("2016-03-18T17:00+01:00");
const t2 = ZonedDateTime.parse("2016-03-18T20:30+01:00");

const r = t1.until(t2, ChronoUnit.MINUTES);
console.log(r);
// -> 210

// also you can:

const r2 = ChronoUnit.MINUTES.between(t1, t2);
console.log(r2);
// -> 210
```

The last option also work, as @aukevanleeuwen shown, with `Duration` and `Period` that allows more sophisticated options.
