### ISSUE TITLE
Insane drop in performance from node 12/13 -> 14/15

### ISSUE THREAD

**Issue by icetbr** [js-joda/js-joda#490]
Hi, I have made a very basic benchmark for date comparison `joda0600.isBefore(joda0700))`.

In node 12.9.1/13.13.0, I got ~772M ops/s.
In node 14.16.1 244 I got ~244M ops/s.
In node 15.14 I got ~55M ops/s.

Here is my repo for testing
https://github.com/icetbr/perf-experiments

Run with
node test/timeTest.js

By the way, I'm pretty sure my benchmark is at fault, I welcome a better version

**Comment by pithu** [comment]
Hello @icetbr thanks for using js-joda and reporting.

Indeed a bit strange how different node versions behave. On my machine i could observe that node 14 has 50%  ops compare to 12 and node 10 has about 20 % compare to 12 for your concrete example. 

I tried to track the problem down by testing the pure business logic that happens behind `isBefore`, by accessing props of the instances directly eq `cmp = a._time._nano - b._time._nano`. This test shows:

```
            |   pure logic     |   isBefore   
node 10     |    180 M ops     |   110 M ops
node 12     |    910 M ops     |   900 M ops
node 14     |    890 M ops     |   320 M ops
``` 

The difference between `pure` and `isBefore`  is mainly that it accesses all logic through class methods. 

**But it seems to be a quite isolated issue, running the benchmarks in our package (see packages/core/benchmark/Readme.md) do not show a big difference in performance between node 12 and node 14.**

Maybe node 14 has some issues optimizing certain class methods calls ?
