### ISSUE TITLE
Zone offset parser doesn't accept "+hh"

### ISSUE THREAD

**Issue by dkhalanskyjb** [js-joda/js-joda#492]
`OffsetDateTime.parse("2020-01-01T00:01:01+00")` throws an exception on 3.2.0.

**Comment by pithu** [comment]
The Offset requires minutes. This should work:
```
OffsetDateTime.parse("2020-01-01T00:01:01+00:00")
// or 
OffsetDateTime.parse("2020-01-01T00:01:01Z")
```
Alternatively you could write an own formatter.

Does this help?

**Comment by dkhalanskyjb** [comment]
Ah, yeah, sorry. I initially thought this was a bug for sure, given that JDK 11 and later allow parsing just `+hh` instead of `+hh:mm`. However, then I looked at the older Java implementations, and it turns out that they also exhibit this behavior, so your implementation is consistent with them. Sorry for the noise!

**Comment by pithu** [comment]
Good to know, probably an interesting backport fix for theeten and js-joda.
