### ISSUE TITLE
Unclear how to convert to/from native Date

### ISSUE THREAD

**Issue by 0xorial** [js-joda/js-joda#494]
It seems like a pretty fundamental operation, but they are not mentioned in the doc. After 10 minutes of search still cannot find how to convert to Date.

**Comment by phueper** [comment]
Hi @0xorial ,

thanks for using js-joda and reporting this issue. 

Please use the following static functions:

https://js-joda.github.io/js-joda/function/index.html#static-function-nativeJs
and
https://js-joda.github.io/js-joda/function/index.html#static-function-convert

I agree that this i not easily to find, we are happy to accept Pull Requests to improve the documentation to find these more easily

Regards, Pattrick

**Comment by pithu** [comment]
I updated the documentation, see https://js-joda.github.io/js-joda/manual/convert-native.html
