### ISSUE TITLE
LocalDateTime.ofInstant() throws a TypeError

### ISSUE THREAD

**Issue by NicoleRauch** [js-joda/js-joda#50]
Hello,

when I invoke

`LocalDateTime.ofInstant(1459546270798)`

I get the following stacktrace:

TypeError: localDateTime.toEpochSecond is not a function
    at SystemDefaultZoneRules.offsetOfLocalDateTime (.../node_modules/js-joda/dist/js-joda.js:5465:41)
    at SystemDefaultZoneRules.offset (.../node_modules/js-joda/dist/js-joda.js:5238:26)
    at Function.ofInstant (.../node_modules/js-joda/dist/js-joda.js:1886:29)

Any ideas?

**Comment by phueper** [comment]
Hey Nicole,

thanks for using js-joda and thanks for reporting this. 
Obviously you have caught a case that we (and the tests we ported) haven't caught yet.
We'll investigate as soon as possible and try to provide a fix.

Regards, Pattrick

**Comment by phueper** [comment]
Hi Nicole,

as per the docs https://doc.esdoc.org/github.com/js-joda/js-joda/class/src/LocalDateTime.js~LocalDateTime.html#static-method-ofInstant the ofInstant method does not accept a number as parameter. Could you please either try LocalDateTime.ofEpochSeconds(...) or LocalDateTime.ofInstant(Instant.ofEpochSecond(...))

Regards, Pattrick

**Comment by pithu** [comment]
Hi Nicole,
it looks like you try to convert the epochmillis from javascript Date object. The recommended and direct way to convert a Date object is:
```
d = new Date(); 
LocalDateTime.from(nativeJs(d))
```
If you you want to convert epochMillis directly,  there is another option beside what patty already mentioned:
```
LocalDateTime.ofInstant(Instant.ofEpochMilli(1459546270798))
```
By default you get the local date time with the locale system default timezone. You have the option to specify a different time-zone as well. see the doc eg.  [nativeJs](https://doc.esdoc.org/github.com/js-joda/js-joda/function/index.html#static-function-nativeJs) or [LocalDateTime.ofInstant](https://doc.esdoc.org/github.com/js-joda/js-joda/class/src/LocalDateTime.js~LocalDateTime.html#static-method-ofInstant)

Regards and have fun Philipp

**Comment by pithu** [comment]
@phueper shall we improve the error message for .ofInstant(number) ?

**Comment by phueper** [comment]
I think that would be a good idea...  A `requireInstance` check would give a more comprehensive error message and probably close this issue?

**Comment by pithu** [comment]
+1

**Comment by pithu** [comment]
btw: you can find the examples in the cheat-sheet http://js-joda.github.io/js-joda/cheat-sheet.html#convert-from-a-javascript-date-or-moment

**Comment by NicoleRauch** [comment]
Hey Pattrick and Philipp,

thanks for your explanations! Sorry, I misread the documentation - now I understand that I need an Instance object instead of a number.

Improving the error message would be extremely helpful :-)

Cheers,
Nicole
