### ISSUE TITLE
LocalDate.atStartOfDayWithZone: inconsistent ts types

### ISSUE THREAD

**Issue by tkurki** [js-joda/js-joda#519]
This js code works:

```
const { LocalDate, ZoneOffset } = require('@js-joda/core')
console.log(LocalDate.of(2021,1,1).atStartOfDayWithZone(ZoneOffset.UTC))
```

but this ts code does not transpile
```
const { LocalDate, ZoneOffset } = require('@js-joda/core')
console.log(LocalDate.of(2021,1,1).atStartOfDayWithZone(ZoneOffset.UTC))

error TS2339: Property 'atStartOfDayWithZone' does not exist on type 'LocalDate'.
```

@js-joda/core@3.2.0
typescript@4.3.5

js-joda.d.ts contains only

```
    atStartOfDay(): LocalDateTime;
    atStartOfDay(zone: ZoneId): ZonedDateTime;
```

Documentation at https://js-joda.github.io/js-joda/class/packages/core/src/LocalDate.js~LocalDate.html is confusing

![image](https://user-images.githubusercontent.com/1049678/126859908-1708351f-84de-43b5-b322-342ff8443721.png)

**Comment by pithu** [comment]
Hello @tkurki, the method atStartOfDayWithZone should not be used, it just exist because we ported this package from Java.

Use atStartOfDay(zoneId) instead, its doing the same thing. 

I hope that helps.

**Comment by pithu** [comment]
But true, the documentation should be updated.

**Comment by pithu** [comment]
fixed
