### ISSUE TITLE
DateTimeFormatter, symbol "a"

### ISSUE THREAD

**Issue by anton-johansson** [js-joda/js-joda#572]
Hey!

The symbol `a` is supposed to give me "AM" or "PM" depending on the time. But when I use that, I'm being asked to install the `@js-joda/locale` plugin:
> IllegalArgumentException: Pattern using (localized) text not implemented, use @js-joda/locale plugin!

I'd prefer not to use the `@js-joda/locale` plugin, I want to handle my formats myself. The package is also quite big because it includes a lot of locales. I'm assuming this is what the package is for, predefined formats. I don't think utilizing `a` should require the locale plugin?

**Comment by pithu** [comment]
Hello @anton-johansson 

Yes am-pm needs locale information, eg for Chinese its

```
const { Locale } = require('@js-joda/locale_zh');
const { DateTimeFormatter, LocalDateTime } = require('@js-joda/core');

const d = LocalDateTime.parse('2018-04-28T12:34');
const f = d.format(DateTimeFormatter.ofPattern('HH:mm a').withLocale(Locale.CHINESE));

console.log(f);  // 12:34 下午
```

If you want to reduce package size you can use one of the prebuilt packages eg `@js-joda/locale_en` and `Locale.ENGLISH` is what you might looking for. Find more documentation here https://js-joda.github.io/js-joda/manual/formatting.html

Does this answer your question?

**Comment by anton-johansson** [comment]
Aha, okay! That makes perfect sense. Thanks for the quick response!
