### ISSUE TITLE
"Offsets must not be equal" creating ZonedDateTime

### ISSUE THREAD

**Issue by StrayAlien** [js-joda/js-joda#575]
Hi all,

First of all, thank you for putting the hard yards and creating such a fine lib. Well done to all involved and a very big thank-you.  

I am implementing a spec in JS that has a fair degree of date handling.  In essence, porting an existing impl from Java to JS/Typescript.  All working okay in Java.  I am having some issues in joda-js.  I'll raise some other tickets as well if need be.

First off the bat: 

One of the spec tests relates to `999999999-12-31T23:59:59.999999999` in zone `Europe/Paris`.  For now, I have monkey patched the joda-js year range validation to match Java's -999999999 to 999999999 (this is a separate issue).

But, the following gives "Offsets must not be equal" on creating the ZonedDateTime.

```
                const z = ZoneRegion.of("Europe/Paris"); // also tried ZoneId.of() here
                const ldt = LocalDateTime.of(999999999, 12, 31, 23, 59, 59, 999999999 )
                const zdt = ZonedDateTime.of(ldt, z);
```

Thank you again, and all help appreciated.

**Comment by pithu** [comment]
At the time we implemented js-joda, we did not want to include third party libs and were therefore bound to the range of MAX_SAFE_INTEGER. This is the reason why we had to limit the year range. There is an internal conversion (I think to seconds) that would exceed the limit.

Changing that would be quite a big rewrite.

What is your reason for a wider year range ?

**Comment by StrayAlien** [comment]
Thanks @pithu - appreciate the response.   The reason for +/- 9 9's is purely spec compliance.  The spec dictates that range and an associated TCK has tests for it.  

This is cause of the "Offsets must not be equal" thing?  Debugging through I see in a function `_offsetInfo` it sees an ldtBefore and ldtAfter as both being the same date - and both with year 999999. So ... kind of looks it.

**Comment by pithu** [comment]
`ZonedDateTime` `compare`  converts the date to epoch seconds. With year 999999999 you are far beyond the javascript max safe integer. That's probably the issue you run into.

**Comment by StrayAlien** [comment]
Thanks @pithu
