### ISSUE TITLE
The dist/ folder is missing

### ISSUE THREAD

**Issue by lukaszciastko** [js-joda/js-joda#586]
Your documentation says:

> To use js-joda from a browser, download either dist/js-joda.min.js or dist/js-joda.js (with sourcemaps for development).

However, the /dist folder was deleted 3 months ago (https://github.com/js-joda/js-joda/commit/a5018fa84331d9a6e0ed6f19970879183518d976).

Please, either revert the change or document how to use this library without a dependency manager. Not all web Frameworks use dependency managers - e.g. Flutter does not.

**Comment by pithu** [comment]
Hi @lukaszciastko, thanks for reporting.

Can you `npm install @js-joda/core` and then use the bundles at `node_modules/@js-joda/core/dist` ? Would that help ?

**Comment by pithu** [comment]
As an alternative you can download distribution files from cdn's eg http://cdn.jsdelivr.net/npm/@js-joda/core@5.0.0/dist/js-joda.js
