### ISSUE TITLE
Issue with using `ZonedDateTime` with lodash

### ISSUE THREAD

**Issue by chenrui333** [js-joda/js-joda#588]
👋  When updating to use js-joda/core v5, I ran into some issue of using ZonedDateTime with lodash for `orderBy`, we ended up using the native sort instead. Let me know if that makes sense.

> TypeError: A conversion from Temporal to a number is not allowed. To compare use the methods .equals(), .compareTo(), .isBefore() or one that is more suitable to your use case.

**Comment by pithu** [comment]
With #548 we disallowed implicit type coercion, because it's error prone and does not makes sense in most cases. This may be the problem you are encountering.

Can you provide a code snippet so I can better understand what your problem is?

**Comment by pithu** [comment]
After thinking about it, i guess what you have to do is to provide a custom compare function to lodash. the default strict equal check is not working anymore (and was not really correct prior version @5.0.0).

As far as i understand the lodash docu `compareTo`  is your friend, e.g. `_.orderBy(..., (zdt1, zdt2) => zdt1.compareTo(zdt2))`

**Comment by chenrui333** [comment]
> With #548 we disallowed implicit type coercion, because it's error prone and does not makes sense in most cases. This may be the problem you are encountering.
> 
> Can you provide a code snippet so I can better understand what your problem is?

yeah, I was aware of that PR change. :)

**Comment by chenrui333** [comment]
> As far as i understand the lodash docu compareTo is your friend, e.g. _.orderBy(..., (zdt1, zdt2) => zdt1.compareTo(zdt2))

Yeah, we tried to modify the code for that, but failed

```
  const sortedEdgesByDate = orderBy(
    edges,
    'node.dateTime',
    options.sort === SortOrder.Desc ? ['desc'] : ['asc']
  ).filter(({ cursor }) => {
```

Failed to override the comparator for `'node.dateTime'`, and we ended up doing the native sort

**Comment by pithu** [comment]
Looks like custom comparators are a wanted feature for lodash, see https://stackoverflow.com/questions/43596210/is-it-possible-to-pass-a-custom-comparator-to-lodashs-sortby-function.

I would recommend ramda js 
```
const { sortWith } = require('ramda');
const { ZonedDateTime } = require('@js-joda/core');

const times = [ZonedDateTime.now().plusDays(20), ZonedDateTime.now(), ZonedDateTime.now().plusDays(2)];

const sorted = sortWith([(a,b) => a.compareTo(b)], times);

console.log(sorted.map(zdt => zdt.toString()));
```

or native sort

```
const { ZonedDateTime } = require('@js-joda/core');

const times = [ZonedDateTime.now().plusDays(20), ZonedDateTime.now(), ZonedDateTime.now().plusDays(2)];

const sorted = times.sort((a,b) => a.compareTo(b));

console.log(sorted.map(zdt => zdt.toString()));
```

Would that help ?

**Comment by pithu** [comment]
I will close it for now, please feel free to reopen the issue, ii you see any further issues.
