### ISSUE TITLE
Zone name is not formatted correctly

### ISSUE THREAD

**Issue by mstawick** [js-joda/js-joda#598]
The "z" pattern always returns the name that the zone was created with (ZoneId.of(name)), instead of the proper abbreviation/name.
If, for instance, I create the zone using ZoneId.of("Europe/Warsaw"), "z", "zz", "zzz", "zzzz" will format it as "Europe/Warsaw", instead of using CET/CEST for the short patterns.

Likewise, if I create the ZoneId.of("CET"), it will always be rendered as "CET", instead of "Central European Time" for the long pattern.

Here's a snippet:
```
const local = LocalDateTime.now();
      const zoneFull = ZoneId.of("Europe/Warsaw");
      const zoneAb = ZoneId.of("CET");

      const full = local.atZone(zoneFull);
      const ab = local.atZone(zoneAb);


      const formatter1 = DateTimeFormatter.ofPattern('z').withLocale(Locale.ENGLISH);
      const formatter2 = DateTimeFormatter.ofPattern('zz').withLocale(Locale.ENGLISH);
      const formatter3 = DateTimeFormatter.ofPattern('zzz').withLocale(Locale.ENGLISH);
      const formatter4 = DateTimeFormatter.ofPattern('zzzz').withLocale(Locale.ENGLISH);

      console.log(
        formatter1.format(full),
        formatter2.format(full),
        formatter3.format(full),
        formatter4.format(full),
      );

      console.log(
        formatter1.format(ab),
        formatter2.format(ab),
        formatter3.format(ab),
        formatter4.format(ab),
      );
```

This produces:
```
Europe/Warsaw Europe/Warsaw Europe/Warsaw Central European Time
CET CET CET CET
```

I checked it in Java, and it works there as expected.

---

And thank you so much for this library. I'm in the process of migrating from MomentJS, and it's so much nicer to use the same API in backend and frontend.

**Comment by pithu** [comment]
Is this a duplicate with #518 ? @phueper was working on it recently
