### ISSUE TITLE
Duration crossing DST boundary is incorrect.

### ISSUE THREAD

**Issue by BillSchumacher** [js-joda/js-joda#608]
```
var date_start = LocalDate.of(2018, 11, 3);
var zoned_start = date_start.atTime(LocalTime.of(19, 0, 0)).atZone(ZoneId.of("America/Chicago"));
var date_end = LocalDate.of(2018, 11, 4);
var zoned_end = date_end.atTime(LocalTime.of(3, 0, 0)).atZone(ZoneId.of("America/Chicago"));
duration = Duration.between(zoned_start, zoned_end).toHours();

console.log(zoned_start.toString(), zoned_end.toString(), duration);
console.log(zoned_start.plusHours(6).toString());
console.log(zoned_start.plusHours(7).toString());
console.log(zoned_start.plusHours(8).toString());
```

produces

```
2018-11-03T19:00-05:00[America/Chicago] 2018-11-04T03:00-06:00[America/Chicago] 9
2018-11-04T01:00-05:00[America/Chicago]
2018-11-04T01:00-06:00[America/Chicago]
2018-11-04T02:00-06:00[America/Chicago]
```
I suspect the error is not advancing time when changing the timezone to -6

postgresql output:
![image](https://user-images.githubusercontent.com/34168009/167909045-78ebb1a1-89af-4202-880d-5fa6cc747cdd.png)

python's zoneinfo output:
```

import zoneinfo
from datetime import datetime, date, time

d = date(2018, 11, 3)
d2 = date(2018, 11, 4)
start_time = time(19)
end_time = time(3)

dt_start = datetime.combine(d, start_time).astimezone(zoneinfo.ZoneInfo("US/Central"))
dt_end = datetime.combine(d2, end_time).astimezone(zoneinfo.ZoneInfo("US/Central"))

print(dt_start, dt_end, dt_end - dt_start)
```
```
2018-11-03 19:00:00-05:00 2018-11-04 03:00:00-06:00 8:00:00
```

**Comment by pithu** [comment]
Hello @BillSchumacher, 

The js-joda Duration considers the DST boundary, thats thee reason why the result is 9 hours.  Assume you start a stopwatch `2018-11-03 19:00:00-05:00` and stop it at `2018-11-04 03:00:00-06:00` the stopwatch would show exactly 9 hours. So i would say its an expected and correct result.

**Comment by BillSchumacher** [comment]
Time was supposed to be set back an hour at 1am CST.

In the example I provided it clearly shows 1am as -5 utc.

Then again at 1am -6 utc. After adding 6 and 7 hours respectively.

An hour after 12pm -5 utc should have been 1am -6 utc.

There is no 1:01 -5 utc as the timezone already would have changed already any minutes calculated during that period to 1am -6 do not exist in real life so the stop watch would say 8 hours.

**Comment by pithu** [comment]
We might talk about different things, from 19 pm to 3 am its 8 hours without a dst, with a dst one hour back you have 8 + 1 = 9 hours. Thats what the java time, threeten and js-joda api says. Therefore i can't see an error.

**Comment by BillSchumacher** [comment]
Is there a way to toggle this?

**Comment by pithu** [comment]
No, but you could convert it to LocalDateTime, so calculation is without DST
```
Duration.between(
   ZonedDateTime.parse("2018-11-03T19:00-05:00[America/Chicago]")
       .toLocalDateTime(), 
   ZonedDateTime.parse("2018-11-04T03:00-06:00[America/Chicago]")
       .toLocalDateTime()
).toHours() // 8
```
