### ISSUE TITLE
extra package tests are failing

### ISSUE THREAD

**Issue by pithu** [js-joda/js-joda#617]
extra package tests are failing on IE 11.0 (Windows 10) two times -> `org.threeten.extra.TestDayOfYear compareTo() test_compareTo FAILED` 

see https://github.com/js-joda/js-joda/runs/7825986595?check_suite_focus=true#step:8:237

@perceptron8 could you have a look ? Is it possible that there is some javascript code that is not compatible with ie11 ? either in the `test` or `src` code. 

We would need to fix this before the next release. We promised our users to be ie11 compatible.

**Comment by perceptron8** [comment]
@pithu As you can see, it's a timeout related problem. On my PC, test_compareTo runs in about 1500 ms, but it seems that there is some limit used in CI setup, where it needs more than 2000 ms and that's too much.

It is definitely not IE11 compatibility issue nor tests itself related problem. I believe it's chai's ridiculously slow `expect` we should blame here. You can verify this by yourself.

Try to run
```console
NODE_ENV=test npx mocha --timeout 5000 --require @babel/register ./test/reference/DayOfYearTest.js
```

>    compareTo()
>      ✔ test_compareTo (1605ms)
>     ✔ test_compareTo_nullDayOfYear
>    equals() / hashCode()
>      ✔ test_equals (1554ms)
>      ✔ test_equals_nullDayOfYear
>      ✔ test_equals_incorrectType

Now edit `assertEquals` (from packages/extra/test/testUtils.js). Replace

```javascript
export function assertEquals(expected, actual, message) {
    if (expected != null || actual != null) {
        if (expected != null) {
            if (typeof expected.equals === 'function') {
                expect(expected.equals(actual), message != null ? message : `${expected} not equals ${actual}`).to.be.true;
            } else {
                expect(expected, message).to.eql(actual);
            }
        } else {
            expect(actual).to.be.null;
        }
    }
}
```

with

```javascript
export function assertEquals(expected, actual, message) {
    if (expected != null || actual != null) {
        if (expected != null) {
            if (typeof expected.equals === 'function') {
                if (!expected.equals(actual)) {
                    throw new Error(message ?? `${expected} not equals ${actual}`);
                }
            } else {
                if (expected !== actual) {
                    throw new Error(message ?? `${expected} !== ${actual}`);
                }
            }
        } else {
            if (actual != null) {
                throw new Error(`${expected} is not null`);
            }
        }
    }
}
```

(linter may complain about nullish coalescing operator, but let's ignore this for now)

Run
```console
NODE_ENV=test npx mocha --timeout 5000 --require @babel/register ./test/reference/DayOfYearTest.js
```
again.

You will get something close to the following.

>    compareTo()
>      ✔ test_compareTo (50ms)
>      ✔ test_compareTo_nullDayOfYear
>    equals() / hashCode()
>      ✔ test_equals (43ms)
>      ✔ test_equals_nullDayOfYear
>      ✔ test_equals_incorrectType

I'll try to investigate what can be done.

**Comment by pithu** [comment]
Interesting, i wonder why expect is so slow. Of course performance optimisation is the best solution. Would be great if you could investigate.

If not possible we can also  reduce number of test counts eg here https://github.com/js-joda/js-joda/blob/32fea33fe0a4fdf614bf85d6e7cd25b80c947f1c/packages/core/test/reference/temporal/IsoFieldsTest.js#L116

Long running tests causing flaky tests on saucelab, so increasing timeout is not a good option.

**Comment by perceptron8** [comment]
Even something as simple as following can be unpredictable:

```javascript
import { strict as assert } from 'node:assert';
import { performance } from 'perf_hooks';

class Period {
	#years;
	#months;
	#days;

	constructor(years, months, days) {
		this.#years = years;
		this.#months = months;
		this.#days = days;
	}
}

const t0 = performance.now();
for (let i = 0; i < 1_000_000; i++) {
	const period = new Period(0, 0, 0);
	assert(period !== null);
}
const t1 = performance.now();

console.log(t1 - t0);
```

```console
$ nvm use 16.16.0
$ node index.js
344.3013160000555
```


```console
$ nvm use 18.7.0
$ node index.js
14.574071999639273
```

~20x difference! Crazy, isn't it?

You may ask: what happens, when you replace `assert` with `expect`?

```javascript
import { expect } from 'chai';
import { performance } from 'perf_hooks';

class Period {
	#years;
	#months;
	#days;

	constructor(years, months, days) {
		this.#years = years;
		this.#months = months;
		this.#days = days;
	}
}

const t0 = performance.now();
for (let i = 0; i < 1_000_000; i++) {
	const period = new Period(0, 0, 0);
	expect(period).to.be.not.null;
}
const t1 = performance.now();

console.log(t1 - t0);
```

```console
$ nvm use 16.16.0
$ node index.js
8459.012095999904
```


```console
$ nvm use 18.7.0
$ node index.js
6816.206538999919
```

Total (best vs worst) difference in performance is close to 450x, which is insane!

Of course I'm not willing to fight with Babel and non-optimizable mess it produces.

What I did in #618 should be enough to get below 2000 ms. ;) When testing `compareTo` and `equals`, it is sufficient to check just 4 cases: A vs A, A vs B, B vs A and B vs B for some A < B (it's even possible to skip last one). As I said earlier, I tried to stay as close as possible to the original (threeten-extra), but I think that this time we can (and should, and even are forced to) make an exception.
