### ISSUE TITLE
Bad bundle

### ISSUE THREAD

**Issue by iseki0** [js-joda/js-joda#619]
Does it OK? Looks the bundle is incorrect.
<img width="434" alt="image" src="https://user-images.githubusercontent.com/13687964/184548954-c550f8e8-5299-41b6-b102-10423c3d8090.png">
Download from: https://cdn.jsdelivr.net/npm/@js-joda/locale@4.8.1/dist/js-joda-locale.min.js

**Comment by pithu** [comment]
Could you please provide a better description:
- What version you are using
- What is your test setup
- What are you expecting
- What is is failing

Anyway your problem might be, that you are not providing a cldr bundle. Using one of the prebuilt packages eg `@js-joda/locale_en-us` might solve your issue. Check https://github.com/js-joda/js-joda/blob/master/packages/locale/README.md and https://js-joda.github.io/js-joda/manual/Locale.html for more details

**Comment by iseki0** [comment]
I means the bundle might be broken, the hypen is disallowed in the place.
