### ISSUE TITLE
ZoneRegion.ofId not yet implemented?

### ISSUE THREAD

**Issue by janitza-mage** [js-joda/js-joda#620]
The doc comment for ZoneRegion.ofId says it is not yet implemented. It looks like it *is* implemented, but it is unclear to me whether the doc comment is outdated or if the implementation is preliminary / incomplete.

It is also confusing whether one should use ZoneRegion.ofId or ZoneId.of to obtain a region ID. The examples for ZonedDateTime suggest to use ZoneId.of, but the code for that just throws an exception and has a comment: "find implementation at ZoneIdFactory", which is yet another source for ZoneId objects, and by a quick look, the "most complete" one.

The documentation should definitely be improved, but as a first step, I'd suggest gathering relevant notes here, to be used as a starting point for documentation. I'd also like to question what the use of methods like ZoneId.of is if they only throw a "not supported" exception and their comment seems to indicate that they won't be supported in the future either.

Thanks for any help!

**Comment by pithu** [comment]
Hi @janitza-mage thanks for using js-joda and reporting this issue.

ZoneIdFactory is not for external use and therefore marked as private and not listed in the docs. We need the ZoneIdFactory class internally, as a workaround for javascript dependency cycle issue.

I am not sure what a good use case is for ZoneRegion, so i would always use ZoneId.of() to obtain the ZoneId. see https://js-joda.github.io/js-joda/manual/ZonedDateTime.html. If something is not working mentioned in the docs as expected please report a bug. i could not find an error eg `ZonedDateTime.now(ZoneId.of("Europe/Paris")).toString();` is working for me.

In doubt a good source of documentation is to check stackoverflow for java.time API, the most stuff should work for js-joda.

I hope that helps a bit.

> The doc comment for ZoneRegion.ofId says it is not yet implemented. It looks like it is implemented, but it is unclear to me whether the doc comment is outdated or if the implementation is preliminary / incomplete.

Indeed, its outdated, i will fix it.

**Comment by janitza-mage** [comment]
I was using the source code as additional documentation. The key misunderstanding on my part was not knowing about this line in ZoneIdFactory.js, function _init():

    ZoneId.of = ZoneIdFactory.of;

The comment in ZoneId says "Find implementation at {@link ZoneIdFactory}", which sounded to me like "use that instead". Let me suggest to change the comment to "Will be patched at run-time to the implementation at {@link ZoneIdFactory}".
