### ISSUE TITLE
Update tzdb to 2022c

### ISSUE THREAD

**Issue by InExtremaRes** [js-joda/js-joda#624]
Is it possible to update this data?

The timezone data is a little outdated. For instance, in my country, the DST change was delayed this year. The change is already in 2022c (maybe 2022b) but js-joda is still using 2021e.

**Comment by pithu** [comment]
Yes i can in the next days

**Comment by pithu** [comment]
BTW: We should think about to shift the minimal timezone package `latest-2012-2022.json` to a new range. Maybe to something like `2016-2026`. WDYT?

**Comment by InExtremaRes** [comment]
I've been thinking about this as well. In my main project at work I'm going with a custom `2010-2030` range, but I'm thinking to change it to `2000-2030` since there are probably old records that predate 2010 (and I don't need to go as back as 1970).

Now, I think a default range `2016-2026` is a good one right now, but, how will the change work? Does it mean deleting the `2012-2022` range or adding the other one alongside? Because if we delete it, is a breaking change for people importing `2012-2022`.

**Comment by pithu** [comment]
> Now, I think a default range 2016-2026 is a good one right now, but, how will the change work? Does it mean deleting the 2012-2022 range or adding the other one alongside? Because if we delete it, is a breaking change for people importing 2012-2022.

good point, we should add a new one, and flag the other one as deprecated.

**Comment by InExtremaRes** [comment]
In this case I think `2016-2026` is a good default.

> [...] we should add a new one, and flag the other one as deprecated.

And what will be the officially recommended replacement for `2012-2022`? Will it be that people chooses between `2016-2026` or `1970-2030` depending on their needs?

Here is a wild idea but, do you think is possible to deploy an utility that allows an user to construct custom ranges using the data already packaged? I imagine a binary in the `@js-joda/timezone` package to which you pass the range as an argument and produces a new `.js` file in the working dir that you can then add to your project. I know this can be done cloning the sources and hacking the generation process (this what I did) but that requires a lot of manual intervention.

**Comment by pithu** [comment]
> Here is a wild idea but, do you think is possible to deploy an utility that allows an user to construct custom ranges using the data already packaged? I imagine a binary in the @js-joda/timezone package to which you pass the range as an argument and produces a new .js file in the working dir that you can then add to your project. I know this can be done cloning the sources and hacking the generation process (this what I did) but that requires a lot of manual intervention.

Possible for sure, would be a combination of an adapted version of `transform-data.js` and a special call to rollup with an adapted rollup config. But might be not that trivial to setup a "clean" implementation.

For the new range, please check my pr

**Comment by pithu** [comment]
should be fixed with #626
