### ISSUE TITLE
extra package tests are failing on windows ie11

### ISSUE THREAD

**Issue by pithu** [js-joda/js-joda#629]
extra package tests are failing on windows ie11, @perceptron8 could you have a look ? Saucelab tests have a problem with Number.isNan

**Comment by pithu** [comment]
eg here https://github.com/js-joda/js-joda/actions/runs/3108662160/jobs/5038103302#step:8:225

**Comment by perceptron8** [comment]
It's great that this happened! Maybe it's not too late to make one little change in `lengthInDays()`.
I'll create PR in a minute.
