### ISSUE TITLE
ISO_LOCAL_DATE_TIME format displays seconds

### ISSUE THREAD

**Issue by stevcooo** [js-joda/js-joda#638]
Hi, I'm trying to format a LocalDateTime to string in ISO format and I'm using ISO_LOCAL_DATE_TIME. But instead of `2011-12-03T10:15:30` I'm receiving `2011-12-03T10:15:30.667`, notice the milliseconds in the end.

This is my code in ember.js:
`return ZonedDateTime.now(ZoneId.of('Europe/Skopje')).format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);`

And this is the output:
![image](https://user-images.githubusercontent.com/533009/197153321-8e3ca8c5-abc1-40b0-be93-debacf35c4c0.png)

According to the [documentation here](https://js-joda.github.io/js-joda/manual/formatting.html), I should receive a 20chars string if I'm using `DateTimeFormatter.ISO_LOCAL_DATE_TIME`

**Comment by pithu** [comment]
Hi @stevcooo, 

you have to create a custom formater in that case:
```
const df = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss");
const zdt = ZonedDateTime.now(ZoneId.of('Europe/Skopje')).format(df);
```
should do it. Does this help?

**Comment by pithu** [comment]
BTW: The documentation shows a parsing example, the millis at the end are optional for parsing, but are used with formatting.
