### ISSUE TITLE
Why `isEqual` and `compareTo` can't deal with null values?

### ISSUE THREAD

**Issue by stevcooo** [js-joda/js-joda#644]
I'm wondering if there is any reason why `isEqual` and `compareTo` can't deal with null values.
We have a use case where we need `localDateTime.isEqual(null)` to return `false` rather than cause an error, and we don't have control over the call to `localDateTime.isEqual`. We can provide more info about our use case if you're interested.

We currently overcome this issue by creating another class that extends `LocalDateTime` and there we override the method like this: 
```
  isEqual(other) {
    return !!other && super.isEqual(other);
  }
```
It will be more elegant if we can change the `isEqual` method in the `LocalDateTime` to:
```
   isEqual(other) {
        return !!other && this.compareTo(other) === 0;
    }
```

Please let me know if you can consider merging such a change in the code, I'll be happy to create a PR.

**Comment by pithu** [comment]
Sounds reasonable. But that's the default behaviour of Java as far as i remember, its long time ago that i wrote some Java code, but i guess there are good reason for it. And this would be breaking change and therefore a major update.

I am open for that, but first i would like better understand, what are the reasons for threeten / java throwing a NullPointer here. Does somebody have some more insights ?

**Comment by perceptron8** [comment]
@stevcooo `LocalDateTime.isEqual` is not the same as `LocalDateTime.equals` - the good news is that if equality related null-safety is needed, you can just use the latter one. :)

---

As for `compareTo`, it should definitely not support nulls.

`Comparable<T>`, which defines `compareTo`, "imposes a total ordering on the objects of each class that implements it" (see https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html for more details).

Let's assume that `LocalDateTime` implements `Comparable<LocalDateTime>`<sup>*</sup>:
- This clearly means that we should be able to compare any two instances of `LocalDateTime`.
- It doesn't mean that we should be able to compare `LocalDateTime` to, say, `String`, `Number`, `Month` or `null`. Such comparisons simply make no sense as `null` is not an instance of `LocalDate` in the same way that `"?"`, `42` and `Month.JANUARY` aren't.

<sup>*</sup> In fact `LocalDateTime` implements `ChronoLocalDateTime` which extends `Comparable<ChronoLocalDateTime>` which makes things a little more complicated.

---

I believe you may find https://blog.joda.org/2012/11/pitfalls-of-consistent-with-equals.html intersesting! ;)

**Comment by stevcooo** [comment]
@perceptron8 Thanks for the explanation. I read your comment and the blog post and I agree entirely with the `compare` method. But the problem occurs when one of my class properties is of type `LocalDateTime`. Let me give you a little bit more context. I'm trying to replace `moment.js` with `js-joda` in my Ember application, and in Ember, the default way of dealing with data is by `Ember Data` which is ORM. This means, whenever one of the properties gets updated the engine compares its new value with its old value (perhaps to optimize the observer pattern). Here comes the trouble, the method used for this is called `isEqual()` and since the `LocalDateTime` implementation of this method doesn't allow `null`, setting a value to a null property is causing exceptions.

My proposal to change the `isEqual` method is strictly about this use case.

**Comment by perceptron8** [comment]
@stevcooo I've checked  `calculateChangedKeys` (Ember Data / record-data.ts) and `isEqual` (ember.js / is-equal.ts) source code and can confirm, that there's not much that can be done on this side. However, I'm still not convinced that `LocalDate.isEqual` implementation should be modified to support nulls.

According to `LocalDate`'s [javadoc](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html#isEqual-java.time.chrono.ChronoLocalDate-) and [js-joda reference](https://js-joda.github.io/js-joda/class/packages/core/src/LocalDate.js~LocalDate.html#instance-method-isEqual) "the other date to compare to" is guaranted to be "not null". There is definitely some code already that depends on this statement (e.g. uses try/catch to deal with null or infers non-nullability of a variable based on this method being called). Last but not least, API of js-joda should be as close as possible to threeten / threeten-extra as to avoid unpleasant surprises (https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

If monkey patching is an option, then maybe you could try something like
```javascript
const originalIsEqual = LocalDate.prototype.isEqual;
LocalDate.prototype.isEqual = function(other) { return !!other && originalIsEqual.call(this, other); }
```
instead?

It's not very elegant, but seems to be less cumbersome than extending `LocalDateTime` just to override `isEqual`.

**Comment by perceptron8** [comment]
@stevcooo Using this pattern you can easily support other joda-time classes like so:

```javascript
for (ctor of [
	LocalDate,
	LocalTime,
	LocalDateTime,
	OffsetDate,
	OffsetTime,
	OffsetDateTime,
	Instant,
	//...
]) {
	const eq = ctor.prototype.isEqual ?? ctor.prototype.equals;
	ctor.prototype.isEqual = function(other) { return !!other && eq.call(this, other); }
}
```

(wrapping original `isEqual` or delegating to `equals` if `isEqual` is not defined)

**Comment by stevcooo** [comment]
Thanks a lot for your suggestion @perceptron8,
I've added it to my code and it works fine.
