### ISSUE TITLE
Docs: Locale page - 404

### ISSUE THREAD

**Issue by Semigradsky** [js-joda/js-joda#662]
The link in navigation: https://js-joda.github.io/js-joda/manual/locale.html is 404

Correct link: `https://js-joda.github.io/js-joda/manual/Locale.html

**Comment by pithu** [comment]
Fixed with commit [001b9b187a7111453ae65a76577df52f2333a53e](https://github.com/js-joda/js-joda/commit/001b9b187a7111453ae65a76577df52f2333a53e)
