### ISSUE TITLE
Define formatting rules for toJSON and toString methods

### ISSUE THREAD

**Issue by alisabzevari** [js-joda/js-joda#675]
I am trying to unify the formatting of `ZonedDateTime` instances throughout the whole application. In other words, I want all my endpoints to serialize date times with UTC (zero) offset. I am currently passing a formatter and call `format` method when I want to serialize objects to JSON. However, this forced us to map datetime fields manually before converting the objects to JSON.

Would it be possible to configure the `toJSON` or `toString` function to use a specific formatter whenver called?

**Comment by pithu** [comment]
Hello @alisabzevari, no i guess that's not possible. The only approach that might work would be to monkey patch `toString`, but neither i know if this would work nor i would recommend that.

**Comment by InExtremaRes** [comment]
Hi @alisabzevari

In my opinion the cleanest way of doing what you want is passing a *replacer function* to `JSON.stringify`. There you can customize the behavior of the jsonification process whatever you want. If you are unfamiliar with replacer functions, is a function you can provide to `JSON.stringify` that will be called with every key and value of the expression being processed and allows you to transform the result at every level; the recursion is already managed by `JSON.stringify`. Here is a small snippet:

```js
// We want to convert this object to a JSON document...
const obj = {
    v1: 123,
    v2: 'hi',
    d1: ZonedDateTime.now(),
    v3: {
        v4: false,
        d2: ZonedDateTime.ofInstant(Instant.EPOCH, ZoneId.UTC),
        v5: {
            d3: ZonedDateTime.now(),
        },
    },
};

// Using this formatter just for the example
const fmt = DateTimeFormatter.ofPattern(`yyyy-MM-dd'T'HH:mm:ss[.SSS]Z`);

// The second argument is the replacer function and in this case CANNOT be an arrow function.
const json = JSON.stringify(obj, function (this, key, value) {
    // Here `value` is already the string produced by `toJSON`, so
    // we must search inside the `this` object for the original value.
    const v = this[key];
    if (v instanceof ZonedDateTime) {
        return v.format(fmt);
    }

    // Every other value must be returned as-is or the whole subtree
    // will be omited in the resulting JSON document.
    return value;
});
```

Of course the function can be extracted and reused the way you need to. You can even use curryfication so the function is parameterized by the *formatter* and it returns the replacer, but that is up to you.

**NOTE:** In the example I'm detecting the existence of a `ZonedDateTime` using `instanceof`, but that might be inadequate depending in your circumstances. If all your imports come from the same "place" that should work OK, but there exists cases (like crossing through realms) where the prototype is different and `instanceof` won't work.

If for whatever reason you can't provide a replacer function, I think your only remaining (global) option is to monkey-patch the prototype of `ZonedDateTime` but that is not supported by the js-joda team. That means, you are on your own; the code might work but the behavior of such a hack could break at any time with any new release, major or minor.

Hope this helps!

**Comment by alisabzevari** [comment]
Thank you for the asnwers.

I think all those approaches would work in different circumstances. But, I don't have access to the `stringify` part of the system. That's being managed by the framework.
I ended up with redefining `toString` methods *after* instantiating the `ZonedDateTime`. This was possible because my datetime type was wrapped in a zod type. So, I could choose an approach similar to monkey patching but not that disruptive.
