### ISSUE TITLE
Potential breaking changes in Moment Timezone data format

### ISSUE THREAD

**Issue by gilmoreorless** [js-joda/js-joda#678]
Hiya, this is a friendly heads-up. I'm planning to do a one-off breaking change release for `moment-timezone` at some (currently unspecified) point in the future, and I'm currently seeking feedback: https://github.com/moment/moment-timezone/issues/1039

One of the potential changes is around the date range and format of the packed JSON data. My understanding is that `js-joda` also uses these packed JSON files — is that correct? If so, I have some questions for you:

1. Do you use the `packed.json` data directly, using your own parser, or do you just reuse the parsing functions in `moment-timezone-utils.js`?
2. Would a change to the packed data format break your project?
3. Would a change to the maximum date range in the data break your project?

A rough idea of some of the format changes is detailed in some example snippets at https://github.com/moment/moment-timezone/issues/1039#issuecomment-1445251293. I'd love to get your feedback.

**Comment by pithu** [comment]
I just saw that the 2038 issue is already fixed, but introduced https://github.com/moment/moment-timezone/issues/999. 

So yes, fixing filesize, would be really important. Either by supplying several ranges of tzdb data (eg +-10 and +-100 years) and / or a by compacting data even more.

I like the idea of having a separate tzdb javascript package, that is feasible also for other libraries.

**Comment by gilmoreorless** [comment]
Thanks for your thoughts!

> I thought moment is "legacy" and "done" and just waiting for the temporal proposal. I wonder how that fits with a major refactoring of Moment ?

This is somewhat explained in the opening part of the issue (`But what about "maintenance mode"?`). I'm only considering this change because:

1. It doesn't touch the core Moment library at all.
2. The changes have a fairly small surface area, and don't involve rewriting large chunks of the codebase. They're not really a major refactoring, just some small tweaks that happen to break the API contract.

That said, the potential change I'm the most hesitant about is extracting the data to one or more separate packages. I haven't properly dug into how it would work, and it might turn out to be too disruptive if a lot of the internals have to change.
