### ISSUE TITLE
Zoneless Date from Instant in Docs

### ISSUE THREAD

**Issue by cedw032** [js-joda/js-joda#682]
A LocalDate should be a Date with no TZ information.
At any given instant there are two possible dates depending on the TZ.
You cannot create a single LocalDate from an Instant alone.
The docs show this as an example though.

<img width="952" alt="Screenshot 2023-04-18 at 19 13 29" src="https://user-images.githubusercontent.com/5538701/232733696-8220f7b2-0a99-45f7-ae99-e79b4bc34249.png">

**Comment by pithu** [comment]
Hi @cedw032, not sure if got your issue. 

However `LocalDate.ofInstant(someInstant)` is valid, see https://js-joda.github.io/js-joda/class/packages/core/src/LocalDate.js~LocalDate.html#static-method-ofInstant . 
It takes `ZoneId.systemDefault()` as defautt Zone.
