### ISSUE TITLE
DateTimeFormatterBuilder.appendValue() 3 arguments: undefined must not be null

### ISSUE THREAD

**Issue by m-jung** [js-joda/js-joda#689]
Calling `DateTimeFormatterBuilder.appendValue()` with 3 arguments results in an `NullPointerException` _undefined must not be null_

## Expected Behavior
The Documentation / TypeScript Definitions should correspond with the actual behavior.

## Current Behavior
_js-joda.d.ts_ defines `appendValue()` with one required and three optional arguments:
```appendValue(field: TemporalField, width?: number, maxWidth?: number, signStyle?: SignStyle): DateTimeFormatterBuilder;```
But using three arguments results in an `NullPointerException` as the call delegates to `_appendValues4()`, which requires `SignStyle` as fourth argument.

## Possible Solution
The TypeScript Definition should either state that one, two or four arguments are reuqired.
```
appendValue(field: TemporalField): DateTimeFormatterBuilder;
appendValue(field: TemporalField, width: number): DateTimeFormatterBuilder;
appendValue(field: TemporalField, width: number, maxWidth: number, signStyle: SignStyle): DateTimeFormatterBuilder;
```
or `DateTimeFormatterBuilder` should implement `_appendValues3()` taking three arguments.

## Steps to Reproduce (for Bugs)
```new DateTimeFormatterBuilder().appendValue(ChronoField.YEAR, 3, 4)```

## Context
The intention was to build an formatter which allows to parse either three or four digit years.

## Your Environment
The affected Version is _@js-joda/core@5.5.3_

**Comment by florian-h05** [comment]
Seems like I have to take a look at this myself.

**Comment by pithu** [comment]
Yes please, would be great if you could provide a PR for it, should be straight forward.
