### ISSUE TITLE
YearQuarter.now(): now.getYear is not a function

### ISSUE THREAD

**Issue by m-jung** [js-joda/js-joda#695]
Calling `YearQuarter.now()` results in an `TypeError:` _now.getYear is not a function_

## Expected Behavior
An instance of `YearQuarter` holding the current year and quarter of current year should be returned.

## Current Behavior
A `TypeError` is raised most likely because of [`YearQuarter:104`](https://github.com/js-joda/js-joda/blob/2f592f179be16991c2f56402cdb2a95125cf06a2/packages/extra/src/YearQuarter.js#L104) where `getYear()` is called, which does not exist on `LocalDate`.

## Possible Solution
Change calls to `getYear()` and `getMonth()` to `year()` and `month()`, which both exist on `LocalDate`.

## Steps to Reproduce (for Bugs)
```YearQuarter.now()```

## Your Environment
The affected Version is _@js-joda/core@5.5.3_

**Comment by pithu** [comment]
Hello @m-jung thanks for reporting. The looks indeed like a bug and missing test coverage. 
I will not find any time to fix this, extra package was from the beginning  community driven only. 
But i would welcome a PR, the fix you proposed sounds good to me and a short test for the case would be great. 
Best Philipp
