### ISSUE TITLE
Missing Requirement of @js-joda/timezone should throw error or give some message

### ISSUE THREAD

**Issue by xanderyzwich** [js-joda/js-joda#702]
Currently attempting to use `ZoneId.of(...)` without having `require('@js-joda/timezone')` results in the page just breaking without any clarity as to why. If this happens there should be some output or error.

**Comment by pithu** [comment]
Hi @xanderyzwich, could you provide some more context to reproduce the issue. eg are you using node or boroser, a bundler, etc.
