### ISSUE TITLE
Why does ZoneId.systemDefault() return SYSTEM?

### ISSUE THREAD

**Issue by mellis481** [js-joda/js-joda#704]
In my application, when I run `ZoneId.systemDefault()`, I get `SYSTEM`. When I run that same line of code in my console when on https://js-joda.github.io, I get `America/New_York`. I also get `America/New_York` in my application when I run `Intl.DateTimeFormat().resolvedOptions().timeZone`.

Why?

**Comment by pithu** [comment]
Hello @mellis481 , did you follow the instructions https://js-joda.github.io/js-joda/manual/ZonedDateTime.html#working-with-time-zones and included the js-joda timezone npm package? Without you don't have any other timezones

**Comment by mellis481** [comment]
@pithu I missed that. Thanks!
