### ISSUE TITLE
Leap year period calculation issue when start date  = 29/02

### ISSUE THREAD

**Issue by Vashev-S** [js-joda/js-joda#705]
Trying to get period between dates INCLUDING last day.
exmpl:  from 2023-01-01 to 2023-12-31 is a whole year.

`
let dtStart = joda.LocalDate.parse('2024-02-29');
let dtEnd = LocalDate.parse('2025-02-28').plusDays(1);
let period = dtStart.until(dtEnd); 
// expect result 'P1Y'
// actual result 'P1Y1D'
`

The one which working fine:
`
let dtStart = joda.LocalDate.parse('2024-02-28');
let dtEnd = LocalDate.parse('2025-02-27').plusDays(1);
let period = dtStart.until(dtEnd); 
// expect result 'P1Y'
// actual  result 'P1Y'
`

**Comment by pithu** [comment]
Isn't that more a theoretical discussion ? Period of one year can be 365 or 366 days. From 2024-02-28 to 2025-02-28 is one year and from 2024-02-29 to 2025-03-01 its one year and one day. IMHO the result is correct. Nevertheless our upstream project threeten and in the java api you get the same results. So this probably more a discussion for the java community.

**Comment by Vashev-S** [comment]
You gave me some thought , thanks.

But for me it is not just theoretical. I want to find whole year  form 2024-02-29.
The result looks strange, Is'nt it?
`
// Very strange result 
const start = LocalDate.parse('2024-02-29')
const end = start.plusYears(1); // '2024-02-28'
start.until(end) // P11M30D

// Another example
const start = LocalDate.parse('2024-02-29')
const end =  LocalDate.parse('2024-03-01')
start.until(end) // P1Y1D

//This one is 100% accurate
const start = LocalDate.parse('2024-02-28')
const end = start.plusYears(1); // '2024-02-28'
start.until(end) // P1Y
`

Perhaps I miss understund how leap years calculation works, but where is P1Y if we start counting from 02.29 ?

**Comment by pithu** [comment]
Indeed, i agree that Period and Date calculation can produce strange results in case of leap years. Especially your first example looks weird. But the second makes sense imo. Eg  `LocalDate.parse('2024-02-29').until(LocalDate.parse('2028-02-29')).toString()` is `P4Y` and `LocalDate.parse('2024-02-29').until(LocalDate.parse('2028-03-01')).toString()` is `P4Y1D`. 
In general i would say its impossible to map an amount of days to a consistent period of years, month and days of month, because years and month do not have a fixed amount of days.

**Comment by Vashev-S** [comment]
I totaly agree that second example make sense.

But I still belive in bug in the first example.

Next condition must be equal with any X and Z 
"X + (Z - Z) = X"
```
const start = LocalDate.parse(X)
const end =  start.plusYears(Z);

const reclaculatedStart = end.plusYears(-Z);

checkEqualty(start , reclaculatedStart ); // Must be true in any case
```
But somehow it doesn't work with "X = '02-29-....'" and  "1 <=  Z  < 4"


I would be REALY happy if you will find misstake in my thoughts.
