### ISSUE TITLE
Issue with WeekField docs

### ISSUE THREAD

**Issue by splurgebudget** [js-joda/js-joda#706]
It looks like something went awry when building the current WeekField docs.  Lots of HTML and tag syntax being shown instead of what is necessary.

You can see it here: https://js-joda.github.io/js-joda/class/packages/locale/src/temporal/WeekFields.js~WeekFields.html

While looking at this doc I also noticed that there isn't any doco for `ordinal`

**Comment by pithu** [comment]
Hi @splurgebudget, thanks for reporting, this might be a copy paste error from the java docu. We are open for PR's to fix it ;)

**Comment by splurgebudget** [comment]
I hear you - if I get a minute I'll fix it up.  Currently trying to launch the app by next Sunday... so in a bit of a crunch and just wanted to make sure it was reported somewhere!
