### ISSUE TITLE
Using English locale packages results in error "cldrData: unknown path main/en/ca-gregorian.json"

### ISSUE THREAD

**Issue by rajalala** [js-joda/js-joda#711]
Hey! First of all, really like the package - especially knowing I'm working with valid dates (once converted to LocalDate of course).

Unfortunately, I'm having issues trying to use any English locale (such as `@js-joda/locale_en`) in a Vue app and am getting the following error:
```
Uncaught (in promise) Error: cldrData: unknown path main/en/ca-gregorian.json
    at cldrData (@js-joda_locale_fi-fi.js?v=0bc6b3d8:12282:19)
    at loadCldrData2 (@js-joda_locale_fi-fi.js?v=0bc6b3d8:13086:21)
    at CldrDateTimeTextProvider2._createStore (@js-joda_locale_fi-fi.js?v=0bc6b3d8:13146:11)
    at CldrDateTimeTextProvider2._findStore (@js-joda_locale_fi-fi.js?v=0bc6b3d8:13140:26)
    at CldrDateTimeTextProvider2.getText (@js-joda_locale_fi-fi.js?v=0bc6b3d8:13123:28)
    at TextPrinterParser2.print (@js-joda_locale_fi-fi.js?v=0bc6b3d8:105:37)
    at CompositePrinterParser2.print (chunk-QKJ6GB7V.js?v=32e1a2e7:3883:20)
    at DateTimeFormatter2._formatTo (chunk-QKJ6GB7V.js?v=32e1a2e7:5514:29)
    at DateTimeFormatter2.format (chunk-QKJ6GB7V.js?v=32e1a2e7:5507:14)
    at LocalDate2.format (chunk-QKJ6GB7V.js?v=32e1a2e7:2312:26)
```

However, I got the prebuilt Finnish locale `(@js-joda/locale_fi-fi")` working just fine. (Thanks for including that package by the way!)

I have some localized formatting functions that - depending on a UI language - will use either Finnish or English. But we aren't following actual English speaking country's date standards and hence flexility of `DateTimeFormatter` would be preferable to using e.g. [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat).

**Following functions are what seem to be causing the issues:**
```
import "@js-joda/timezone";
import { Locale as LocaleEn } from "@js-joda/locale_en";
import { Locale as LocaleFi } from "@js-joda/locale_fi-fi";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Locale } from "@js-joda/locale";
import { DateTimeFormatter, LocalDate } from "@js-joda/core";

/**
 * Formats date string from 2000-01-28 format into Jan 28-formatted string
 */
export const formatShortMonthDate = (date: string) => {
    return formatWithLocale(date, DateTimeFormatter.ofPattern("MMM d"));
};

/**
 * Formats 2000-01-28 style date strings into Pe 28.1. / Fri 28.1. style strings
 */
export const formatDayOfWeekAndDate = (date: string) => {
  const format = DateTimeFormatter.ofPattern("eee d.M.");
  return formatWithLocale(date, format);
};
```

And here are the functions those two above utilize. Function `getUiLocale` decides based on UI language (`isFinnish` is a function that check's localization library's current language) what locale to use. That is probably the cause of my issues. 

```
const getUiLocale = () => {
  return isFinnish() ? new LocaleFi("fi") : /* what should I do here? */;
  // I've tried at least the following:
  // LocaleEn.US;
  // LocaleEn.UK;
  // LocaleEn.ENGLISH;
  // new LocaleEn("en");
  // new LocaleEn("en-US");
};

/**
 * Formats date in a locale-aware manner according to provided format string. Uses UI locale from Vue.
 * @param date date to format as either Date or ISO 8601 string.
 * @param format format as js-joda DateTimeFormatter
 * @throws ValidationError if date is an invalid date
 */
const formatWithLocale = (date: Date | string, format: DateTimeFormatter) => {
  const localDate = toLocalDate(date); // Converting to LocalDate works as a validation step
  return localDate.format(format.withLocale(getUiLocale()));
};

/**
 * Convert from Date or date string to a js-joda LocalDate
 * @param date JavaScript Date or date string (ISO format - though allowing one-digit date and month) to convert
 * @throws ValidationError if date is an invalid date
 */
const toLocalDate = (date: Date | string): LocalDate => {
  return toLocalDateWithPattern(date, "uuuu-M-d");
};
```

Finally, these are the packages I've installed:
```
"@js-joda/core": "^5.6.1",
"@js-joda/locale": "^4.8.12",
"@js-joda/locale_en": "^4.8.11",
"@js-joda/locale_fi-fi": "^4.8.11",
"@js-joda/timezone": "^2.18.2",
```

I've also tried other English locale packages (locale_en-us and locale_en-gb) but those have resulted in the same error. Any ideas what could be going wrong?

Edit: as further, hopefully helpful, detail:
Defining English locale in the following way allows our unit test (with `vitest`) to pass but causes an error `Uncaught ReferenceError: process is not defined` in the browser.
```
import { Locale } from "@js-joda/locale";

const getUiLocale = (): Locale => {
  return isFinnish() ? new LocaleFi("fi") : new Locale("en");
};
```

Any other definition (that I've tried to far) resulted in that `Error: cldrData: unknown path main/en/ca-gregorian.json` in both the browser and the tests.

**Comment by rajalala** [comment]
My colleague just noticed this issue in depracated js-joda-locale repo [#93 Add possibility to load multiple locales](https://github.com/js-joda/js-joda-locale/issues/93) which has also been mentioned (#442) in 2020 in this repo.

So is that still the case that it is not possible to use multiple locales? Any ideas how complex of an issue that is and whether there could be any workarounds?

**Comment by pithu** [comment]
Yes that's correct, you cant import multiple locale packages:

```
import { Locale as LocaleEn } from "@js-joda/locale_en";
// Don't work, second import overwrites the first import
import { Locale as LocaleFi } from "@js-joda/locale_fi-fi";
```

But you can build your own bundle, Please follow the Readme in the locale package. 
Good starting point is the rollup config `https://github.com/js-joda/js-joda/blob/main/packages/locale/rollup-examples.config.js` and the npm command `npm run build-examples`

I hope that helps.

**Comment by rajalala** [comment]
Thank you @pithu for a quick reply! I'll look into bundling.
