### ISSUE TITLE
Duration.plusDuration seems to be missing from type definitions

### ISSUE THREAD

**Issue by syxolk** [js-joda/js-joda#712]
The `plusDuration` method of the `Duration` class is documented here: https://js-joda.github.io/js-joda/class/packages/core/src/Duration.js~Duration.html#instance-method-plusDuration

However, when I have the following Typescript code

```typescript
import { Duration } from "@js-joda/core";

function main() {
    const a = Duration.ofHours(10);
    const b = Duration.ofMinutes(2);
    console.log(a.plusDuration(b));
}
```

Typescript will complain with:

```
Property 'plusDuration' does not exist on type 'Duration'.
```

My workaround is to use this:

```typescript
a.plusMillis(b.toMillis())
```

My versions:
- `@js-joda/core`: 5.6.1
- `typescript`: 5.1.6
- Node.js: 20.5.1

**Comment by pithu** [comment]
Hi @syxolk. 

It is implement, but seems to be missing in the typescript definitions here https://github.com/js-joda/js-joda/blob/main/packages/core/typings/js-joda.d.ts#L1122

As an workaround use `duration.plus()` instead and / or open a PR adding plusDuration to the typings.

I hope that helps.
