### ISSUE TITLE
Adding a formatter for Period/Duration

### ISSUE THREAD

**Issue by lindboe** [js-joda/js-joda#718]
Thanks for this awesome library!

Would you be open to a contribution of a formatter for Period and Duration? I'm coming from joda-time which has `PeriodFormatter`, for example. I'm happy to see if I can contribute this if I get a little guidance on how you'd like this to be approached. (I see the README mentions a desire to refactor the existing formatter).

**Comment by pithu** [comment]
Hello @lindboe, 

thank you, for using js-joda and you are very welcome to contribute. We decided to follow quite strictly the threeten API, it is somehow the predecessor project from joda-time. If you find something in the threeten API that is missing in js-joda we are open for PR's.

Here you find the homepage of threeten https://www.threeten.org/threetenbp/. I guess formatter are located in the extra module https://www.threeten.org/threeten-extra/ and should be ported to our extra package https://github.com/js-joda/js-joda/tree/main/packages/extra.
