### ISSUE TITLE
Mexico stopped using DST last year, but time.ZonedDateTime.now() is still shifting the time by one hour.

### ISSUE THREAD

**Issue by adicorrales** [js-joda/js-joda#719]
Since first Sunday of April (2024), when calling `time.ZonedDateTime.now()` (in openHAB) js-joda returns the time shifted by one hour as in DST for region=Mexico. But Mexico quit using DST last year. Ubuntu server time is ok. Log timestamps are ok.  The log when just call joda `.now()` gives:

`2024-04-12 10:42:26.750 [INFO ] [ab.automation.script.ui.quick_script] - 2024-04-12T11:42:26.742-05:00[SYSTEM]  `

Java `now()` returns the correct time in exactly the same environment:

`2024-04-12 10:42:26.753 [INFO ] [ab.automation.script.ui.quick_script] - 2024-04-12T10:42:26.751611429-06:00[America/Mexico_City]`

**Comment by pithu** [comment]
Hello @adicorrales, thanks for reporting this issue. 

The latest version of js-joda is using 2023c of iana tz db https://www.iana.org/time-zones, what's a bit behind the latest version there is 2023d and 2024a. I can update that in the next days.

But the change about Mexico DST is included in 2022f (https://mm.icann.org/pipermail/tz-announce/2022-October/000075.html) therefore, when using the latest version of @js-joda/timezone version `2.18.3`. 

Is your project using the latest version of js-joda ? If so could you give a more concrete example?

The following test with latest js-joda version seems correct to me
```
ZonedDateTime.now(ZoneId.of('America/Mexico_City')).toString();
// '2024-04-14T01:40:51.924-06:00[America/Mexico_City]'
```

**Comment by adicorrales** [comment]
Understood. I'll pass this comment to openHAB developer to find out.

**Comment by adicorrales** [comment]
Just to close this: Developer where joda is being used confirm they are using a recent joda version which returns the correct UTS, so, the issue is on their side.

Thank you!
