### ISSUE TITLE
YearMonth is lacking toString() in type definition

### ISSUE THREAD

**Issue by fluidsonic** [js-joda/js-joda#725]
In the TypeScript definitions:

- `YearMonth` has no explicitly overridden `toString()` in its type definition.
- `LocalDate` and others do have an explicitly overridden `toString()` in its type definition.

When calling `toString()` on a `YearMonth` (which returns an ISO-representation), it causes a false-positive ESLint warning:

> ESLint: 'YearMonth.of(2024, 1)' will evaluate to '[object Object]' when stringified.(@typescript-eslint/no-base-to-string)

<img width="868" alt="image" src="https://github.com/js-joda/js-joda/assets/85242/b940e9c3-43c7-4c47-887b-739653b519b8">

(It might be worth double-checking all classes with a custom `toString()` implementation.)

**Comment by pithu** [comment]
Hi @fluidsonic, thanks for reporting, looks like its missing in typings https://github.com/js-joda/js-joda/blob/main/packages/core/typings/js-joda.d.ts#L1562.

We are open for PR's

**Comment by SaichandChowdary** [comment]
@pithu I'd like to work on this one, can you assign it to me.

**Comment by pithu** [comment]
Sure 👍 , could you please check if toString is missing at other places in typings

**Comment by SaichandChowdary** [comment]
PR - https://github.com/js-joda/js-joda/pull/727

**Comment by oliveryasuna** [comment]
@pithu This can be closed.
