### ISSUE TITLE
ZoneId.of('America/Chicago') returns error message when creating a date

### ISSUE THREAD

**Issue by briandee** [js-joda/js-joda#739]
Node Version 20.10
@js-joda/core version 5.6.3
Typescript version 4.7.3

Test Code

import { ZoneId } from '@js-joda/core'
import '@js-joda/timezone'

const cstTimeZone = ZoneId.of('America/Chicago')
const newEnglandZone = ZoneId.of('America/New_York')
Exception thrown

{"msg":"This exception wasn't handled DateTimeException: unsupported ZoneId:America/New_York"}

export const  toDate = (date:string,  time:string) =>{
    const _date = LocalDate.parse(date)
    const _time = LocalTime.parse(time)
    const zdt =  ZonedDateTime.of(_date, _time, ZoneId.of('America/Chicago'));
    return new Date(zdt.toInstant().toEpochMilli())
}
const zdtDate =  toDate('2024-09-30', '08:30:00')
After executing this function

{"msg":"This exception wasn't handled DateTimeException: unsupported ZoneId:America/Chicago"}

**Comment by pithu** [comment]
Hello @briandee 
Works form me with `@js-joda/core - 5.6.3` and `@js-joda/timezone - 2.21.1-2024a`
What version of @js-joda/timezone are you using ?

**Comment by briandee** [comment]
Thank you, for your response. It turns out the @js-joda/timezone was not installed after I did npm i @js-joda/timezone. I checked for it in my package.json and realized that it wasn't there. Many thanks, I close the issue.

**Comment by briandee** [comment]
My bad, it turns out that I hadn't properly installed the @js-joda/timezone package
