### ISSUE TITLE
Long patterns for month (MMMMM) and day (EEEEE) inconsistent with SimpleDateFormat

### ISSUE THREAD

**Issue by janoma** [js-joda/js-joda#743]
The [formatting documentation](https://js-joda.github.io/js-joda/manual/formatting.html) states (emphasis mine):

> Date and time formats are **specified** by date and time pattern strings using [Java SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) codes.

In `SimpleDateFormat`, name of day in week (`E`) has a presentation of **Text**, and month in year (`M`) has a presentation of **Number** if the pattern has less than 3 letters (`M` and `MM`), and **Text** otherwise. It also specifies:

> **Text:** For formatting, if the number of pattern letters is 4 or more, the full form is used (...)

which means that patterns like `MMMM`, `MMMMM` and `MMMMMM` should yield the same result:

```ts
import { DateTimeFormatter, LocalDate } from '@js-joda/core';
import { Locale } from '@js-joda/locale_en-us';

const date = LocalDate.of(2024, 12, 9);
const pattern4 = DateTimeFormatter.ofPattern('MMMM').withLocale(Locale.US);
const pattern5 = DateTimeFormatter.ofPattern('MMMMM').withLocale(Locale.US);
const pattern6 = DateTimeFormatter.ofPattern('MMMMMM').withLocale(Locale.US);
```

Here, all 3 patterns should result in `'December'` when doing `date.format(patternN)`. However, the actual results are
```ts
date.format(pattern4); // 'December'
date.format(pattern5); // 'D'
date.format(pattern6); // throws
```

Analogous results for name of day in week with the `EEEEE` and `EEEEEE` patterns.

Note that this *could be* justified with your own documentation, as the examples for month-of-year and day-of-week are `7; 07; Jul; July; J` and `2; Tue; Tuesday; T`, respectively. However, this is still inconsistent with the linked Java documentation.

I do not know if this is a bug in the code or in the documentation (or if maybe I just missed something else entirely). I suspect changing the behavior of the code is riskier as it would be backwards incompatible. If it's considered a documentation bug, please update it to explain the difference in behavior for these long text patterns. I can give it a go myself and create a PR for that, but I want to know if there's agreement this should be updated at all.

Using `@js-joda/core` 5.6.3 and `@js-joda/locale_en-us` 4.14.0.

**Comment by pithu** [comment]
Hello @janoma, 

thanks for reporting, sounds like an upstream issue, maybe better report to threetenbp or openjdk community, since jdk give the same results.

I would be also open for a PR  "fixing" the documentation. Would it make sense to set a pattern with more then 4 letters ?

**Comment by janoma** [comment]
Oh dang, I completely forgot to check the actual Java behavior and assumed it's remained consistent over the years, especially since by this point Java SE 7 is over a decade old.

I can create a PR with updates to clarify the following cases:
* Month and day work as `SimpleDateFormat` from 1 to 4 characters.
* A 5 characters pattern produces a single character. Is it OK to call this an "initial"? I haven't looked at the implementation. Tuesday and Thursday result in `'T'` in English (in case somebody expects this function to be injective), but I don't know if it's always an initial in other languages. We can always say something like "locale-specific single character, usually the initial".
* A pattern with 6 characters or longer is unsupported.

Thanks for responding so quickly @pithu, let me know what you think.

**Comment by janoma** [comment]
Created PR with explanation and examples. Let me know if I should trim it down because I prefer to fall on the comprehensive side of things.

For reference, I tested with various flavors of Java (1.8, 11, 17 and 23) and they were all consistent with their documentation, that is, I got the long day and month names and no failures.

I also looked a little deeper and noticed that js-joda simply has more symbols than `SimpleDateFormat`, so I incorporated that into the documentation too, to make it clear it is not the same specification.

**Comment by janoma** [comment]
Thanks for merging @pithu, but I now realize the HTML version doesn't get automatically updated by the build. I built all the packages and then ran `build-esdoc` from `main`, but I get more files than I was expecting in the diff:

```
	modified:   docs/index.html
	modified:   docs/index.json
	modified:   docs/inject/script/0-index.js
	modified:   docs/inject/script/0-js-joda.min.js
	modified:   docs/manual/formatting.html
	modified:   docs/manual/index.html
	modified:   docs/source.html
```

This is probably fine but I wanted to confirm first. I can create a PR with those, or only with `docs/manual` and `docs/index.html`. I'm unsure about `docs/index.json`, because it contains many local paths, apart from the actual content of `formatting.md` inline. Or you can do it yourself, but I don't want to impose more work on you.
