### ISSUE TITLE
Converting milliseconds to a LocalDate

### ISSUE THREAD

**Issue by cressie176** [js-joda/js-joda#85]
Thanks for your efforts porting Joda. A very worthy cause. However I'm a bit stuck...

I'm trying to get a local date from the a time in milliseconds. The code needs to work on developer machines running in Europe/London (and potentially other timezones), but also on a CI server and production servers running in UTC.

I've managed to get things working for just Europe/London by hard coding the ZoneOffset, but this will fail in other environments and when Europe/London moves out of daylight savings.
```js
const zoneOffset = ZoneOffset.of('+01:00')
const today = LocalDateTime.ofEpochSecond(millis / 1000, zoneOffset).toLocalDate()
```
So far I haven't found a way to get the system offset using js-joda. Is this possible?

**Comment by cressie176** [comment]
Looks like I'm going to need the unimplemented timezone functionality :(

**Comment by phueper** [comment]
Hi @cressie176, first of all thanks for reporting, yes, you might need the missing timezone functionality, but have you looked at the `Instant` class? https://js-joda.github.io/js-joda/esdoc/class/src/Instant.js~Instant.html#static-method-ofEpochMilli is used to represent an instantaneous point on the timeline (which seems to be what you describe) and can be converted to a `LocalDateTime` e.g. using the `ofInstant` function https://js-joda.github.io/js-joda/esdoc/class/src/LocalDateTime.js~LocalDateTime.html#static-method-ofInstant which uses the systemDefault Timezone by default, but can also be passed a zone (with offset) ... the question of course would be how you retrieve your milliseconds and if they are "epochMillis"  or if they have some kind of timezone in their value?

**Comment by cressie176** [comment]
Thanks for the response. I think I misrepresented the problem  (always takes me a while to warm up the date processing part of my brain). Now that I've thought about it some more I think I need to get the current local date for a remote user based on their timezone (which could be different to that of the server). 

The problem is that js-joda doesn't yet have timezone support (not a criticism - I think it's awesome that you're porting joda), so I need to get the offset some other way. ```moment-timezone``` does support timezones and can give me the current offset.

```js
const timezone = 'Europe/London'
const now = clock.now()
const offset = -moment.tz.zone(timezone).offset(now)
const instant = Instant.ofEpochMilli(now)
const zoneId = ZoneOffset.ofTotalMinutes(offset)
const today = LocalDateTime.ofInstant(instant, zoneId).toLocalDate()
```

It's pretty horrid but I can't think of a better alternative :(

**Comment by cressie176** [comment]
Using zoneinfo is slightly nicer if you don't mind using ```_utcoffset()``` ...

```js
const zoneinfo = require('zoneinfo')
const joda = require('js-joda')
const LocalDateTime = joda.LocalDateTime
const ZoneOffset = joda.ZoneOffset
const Instant = joda.Instant

const now = clock.now()
const offset = new zoneinfo.TZDate(now, 'Europe/London')._utcoffset()
const zoneId = ZoneOffset.ofTotalMinutes(offset)
const instant = Instant.ofEpochMilli(now)
const today = LocalDateTime.ofInstant(instant, zoneId).toLocalDate()
```

**Comment by cressie176** [comment]
FYI... ended up creating a module to do it. https://github.com/guidesmiths/world-clock

**Comment by phueper** [comment]
:+1:

**Comment by pithu** [comment]
Hello @cressie176, 

thx a lot for showing this very interesting approach. I never heard about the  npm lib `zoneinfo` that is using the timezone database directly from ths os. should work well for server code on a unix like operating system.

timezone support for js-joda is really the next thing on my timeline. I will start implementing it very soon. I guess its the most wanted, most missing feature and its not really much work to implement it.

But be aware, if you use ZoneRegion with the current js-joda version, that there is still some code missing that is handling the daylight saving transitions. During a DST gap/ overlap js-joda might produce non standard results. 

And as a hint: To keep things simple, always try to calculate the local date on the user machine. Lets say you have a point on the timeline in milliseconds of the epoch, send the epoch millis to the browser of the user and do the LocalDate calculation there:

    LocalDate.ofInstant(Instant.ofEpochMilli( epochMillis ))

**Comment by cressie176** [comment]
Thanks for the heads up. I've subscribed to #32
